package io.invenlio.fulfillment;
import io.swagger.v3.oas.annotations.Operation;import io.swagger.v3.oas.annotations.security.SecurityRequirement;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.util.*;import org.springframework.web.bind.annotation.*;
@RestController@RequestMapping("/api/v1")@SecurityRequirement(name="bearerAuth")class FulfillmentController{private final FulfillmentService service;FulfillmentController(FulfillmentService s){service=s;}
 @Operation(summary="Create a pick list from an allocated sales order")@PostMapping("/pick-lists")FulfillmentService.PickList create(@Valid@RequestBody CreatePick r){return service.createPickList(r.salesOrderId,r.packingLocationId);}
 @Operation(summary="List tenant pick lists")@GetMapping("/pick-lists")List<FulfillmentService.PickList>list(@RequestParam(required=false)UUID salesOrderId,@RequestParam(required=false)UUID warehouseId,@RequestParam(required=false)String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String sort){return service.listPicks(salesOrderId,warehouseId,status,page,size,sort);}
 @GetMapping("/pick-lists/{id}")FulfillmentService.PickList get(@PathVariable UUID id){return service.getPick(id);}
 @Operation(summary="Start picking")@PostMapping("/pick-lists/{id}/start")FulfillmentService.PickList start(@PathVariable UUID id,@Valid@RequestBody Version r){return service.start(id,r.version);}
 @Operation(summary="Complete a task and atomically move reserved stock to packing")@PostMapping("/pick-lists/{id}/tasks/{taskId}/complete")FulfillmentService.PickList completeTask(@PathVariable UUID id,@PathVariable UUID taskId,@RequestHeader("Idempotency-Key")@NotBlank String key,@Valid@RequestBody Version r){return service.completeTask(id,taskId,r.version,key);}
 @Operation(summary="Open a packing session for a completed pick list")@PostMapping("/packing-sessions")FulfillmentService.PackingSession session(@Valid@RequestBody CreateSession r){return service.createSession(r.pickListId);}
 @GetMapping("/packing-sessions/{id}")FulfillmentService.PackingSession getSession(@PathVariable UUID id){return service.getSession(id);}
 @Operation(summary="List tenant packing sessions for resumable packing work")@GetMapping("/packing-sessions")List<FulfillmentService.PackingSession>listSessions(@RequestParam(required=false)UUID salesOrderId,@RequestParam(required=false)String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return service.listSessions(salesOrderId,status,page,size);}
 @Operation(summary="Create a package")@PostMapping("/packing-sessions/{id}/packages")FulfillmentService.PackageView createPackage(@PathVariable UUID id,@Valid@RequestBody PackageRequest r){return service.createPackage(id,new FulfillmentService.PackageCommand(r.weightGrams,r.lengthMm,r.widthMm,r.heightMm));}
 @Operation(summary="Add some or all of a picked task to a package")@PostMapping("/packing-sessions/{id}/packages/{packageId}/items")FulfillmentService.PackageView addItem(@PathVariable UUID id,@PathVariable UUID packageId,@Valid@RequestBody ItemRequest r){return service.addItem(id,packageId,r.pickTaskId,new BigDecimal(r.quantity));}
 @Operation(summary="Seal a non-empty package")@PostMapping("/packing-sessions/{id}/packages/{packageId}/complete")FulfillmentService.PackageView completePackage(@PathVariable UUID id,@PathVariable UUID packageId,@Valid@RequestBody Version r){return service.completePackage(id,packageId,r.version);}
 @Operation(summary="Complete packing after all picked quantities are packaged")@PostMapping("/packing-sessions/{id}/complete")FulfillmentService.PackingSession completeSession(@PathVariable UUID id,@Valid@RequestBody Version r){return service.completeSession(id,r.version);}
 record CreatePick(@NotNull UUID salesOrderId,@NotNull UUID packingLocationId){}record CreateSession(@NotNull UUID pickListId){}record Version(@PositiveOrZero long version){}record PackageRequest(@PositiveOrZero Long weightGrams,@PositiveOrZero Long lengthMm,@PositiveOrZero Long widthMm,@PositiveOrZero Long heightMm){}record ItemRequest(@NotNull UUID pickTaskId,@NotBlank@Pattern(regexp="[0-9]{1,13}(\\.[0-9]{1,6})?") String quantity){}
}
