package io.invenlio.warehouse;
import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;
@Entity @Table(name="warehouse_locations") class StorageLocation{
 enum Type{AISLE,RACK,SHELF,BIN,FLOOR,PALLET_POSITION,STAGING,RECEIVING,PACKING,SHIPPING,RETURNS,QUARANTINE,DAMAGED}enum Status{ACTIVE,BLOCKED,INACTIVE,ARCHIVED}
 @Id UUID id;@Column(name="tenant_id")UUID tenantId;@Column(name="warehouse_id")UUID warehouseId;@Column(name="zone_id")UUID zoneId;@Column(name="parent_location_id")UUID parentId;String code;@Column(name="normalized_code")String normalizedCode;String name;@Enumerated(EnumType.STRING)Type type;@Enumerated(EnumType.STRING)Status status;int sequence;@Column(name="scan_code")String scanCode;@Column(name="normalized_scan_code")String normalizedScanCode;@Column(name="max_weight_grams")Long maxWeight;@Column(name="max_volume_cubic_mm")Long maxVolume;@Column(name="max_pallets")Integer maxPallets;@Column(name="length_mm")Long length;@Column(name="width_mm")Long width;@Column(name="height_mm")Long height;@Column(name="created_at")Instant created;@Column(name="updated_at")Instant updated;@Version long version;
 protected StorageLocation(){}
 StorageLocation(UUID t,UUID w,UUID z,UUID p,String c,String n,Type type,int seq,String scan,Long weight,Long volume,Integer pallets,Long length,Long width,Long height){id=UUID.randomUUID();tenantId=t;warehouseId=w;zoneId=z;parentId=p;code=normalizedCode=Warehouse.norm(c);name=optional(n);this.type=type;sequence=seq;scanCode=normalizedScanCode=Warehouse.norm(scan);capacity(weight,volume,pallets,length,width,height);status=Status.ACTIVE;created=updated=Instant.now();}
 void update(UUID z,String n,Type type,int seq,Long weight,Long volume,Integer pallets,Long length,Long width,Long height,long v){check(v);if(status==Status.ARCHIVED)throw new WarehouseException("INVALID_LOCATION_TRANSITION","Archived location cannot be updated");zoneId=z;name=optional(n);this.type=type;sequence=seq;capacity(weight,volume,pallets,length,width,height);updated=Instant.now();}
 void move(UUID p,long v){check(v);if(status==Status.ARCHIVED)throw new WarehouseException("INVALID_LOCATION_TRANSITION","Archived location cannot move");if(id.equals(p))throw new WarehouseException("LOCATION_CYCLE","Location cannot parent itself");parentId=p;updated=Instant.now();}
 void block(long v){check(v);if(status==Status.BLOCKED)throw new WarehouseException("LOCATION_ALREADY_BLOCKED","Location is already blocked");if(status!=Status.ACTIVE)throw new WarehouseException("INVALID_LOCATION_TRANSITION","Only an active location can be blocked");status=Status.BLOCKED;updated=Instant.now();}
 void unblock(long v){check(v);if(status!=Status.BLOCKED)throw new WarehouseException("INVALID_LOCATION_TRANSITION","Only a blocked location can be unblocked");status=Status.ACTIVE;updated=Instant.now();}
 void archive(long v){check(v);if(status==Status.ARCHIVED)throw new WarehouseException("INVALID_LOCATION_TRANSITION","Location is already archived");status=Status.ARCHIVED;updated=Instant.now();}
 private void check(long v){if(version!=v)throw new WarehouseException("CONCURRENT_MODIFICATION","Stale location version");}
 private void capacity(Long weight,Long volume,Integer pallets,Long l,Long w,Long h){valid(weight);valid(volume);valid(l);valid(w);valid(h);if(pallets!=null&&pallets<0)throw new WarehouseException("INVALID_CAPACITY","Capacity cannot be negative");maxWeight=weight;maxVolume=volume;maxPallets=pallets;length=l;width=w;height=h;}
 private static void valid(Long v){if(v!=null&&v<0)throw new WarehouseException("INVALID_CAPACITY","Capacity and dimensions cannot be negative");}
 private static String optional(String v){if(v==null)return null;v=v.trim();if(v.length()>160)throw new WarehouseException("INVALID_INPUT","Name is too long");return v.isEmpty()?null:v;}
}
