package io.invenlio.warehouse;
import jakarta.persistence.*;import java.time.*;import java.util.UUID;
@Entity @Table(name="warehouses") class Warehouse{
 enum Status{DRAFT,ACTIVE,INACTIVE,ARCHIVED}@Id UUID id;@Column(name="tenant_id")UUID tenantId;String code;@Column(name="normalized_code")String normalizedCode;String name;@Enumerated(EnumType.STRING)Status status;String timezone;@Column(name="address_line1")String line1;@Column(name="address_line2")String line2;@Column(name="postal_code")String postal;String city;@Column(name="state_region")String region;@Column(name="country_code")String country;@Column(name="created_at")Instant created;@Column(name="updated_at")Instant updated;@Version long version;
 protected Warehouse(){}
 Warehouse(UUID t,String c,String n,String tz,String l1,String l2,String pc,String city,String region,String country){id=UUID.randomUUID();tenantId=t;apply(c,n,tz,l1,l2,pc,city,region,country);status=Status.DRAFT;created=updated=Instant.now();}
 void update(String c,String n,String tz,String l1,String l2,String pc,String city,String region,String country,long v){check(v);String normalized=norm(c);if(status!=Status.DRAFT&&!normalized.equals(normalizedCode))throw new WarehouseException("WAREHOUSE_CODE_IMMUTABLE","Code is immutable after activation");apply(c,n,tz,l1,l2,pc,city,region,country);updated=Instant.now();}
 private void apply(String c,String n,String tz,String l1,String l2,String pc,String city,String region,String country){setCode(c);name=req(n,160);try{timezone=ZoneId.of(tz).getId();}catch(Exception e){throw new WarehouseException("INVALID_TIMEZONE","Invalid IANA timezone");}line1=l1;line2=l2;postal=pc;this.city=city;this.region=region;this.country=country==null?null:country.trim().toUpperCase();if(this.country!=null&&!this.country.matches("[A-Z]{2}"))throw new WarehouseException("INVALID_COUNTRY","Country must be ISO alpha-2");}
 void transition(Status next,long v){check(v);boolean ok=switch(status){case DRAFT->next==Status.ACTIVE||next==Status.ARCHIVED;case ACTIVE->next==Status.INACTIVE;case INACTIVE->next==Status.ACTIVE||next==Status.ARCHIVED;case ARCHIVED->false;};if(!ok)throw new WarehouseException("INVALID_WAREHOUSE_TRANSITION","Invalid transition");status=next;updated=Instant.now();}
 void check(long v){if(version!=v)throw new WarehouseException("CONCURRENT_MODIFICATION","Stale warehouse version");}private void setCode(String c){code=normalizedCode=norm(c);}static String norm(String s){String v=req(s,40).toUpperCase().replaceAll("\\s+","-");if(!v.matches("[A-Z0-9][A-Z0-9._-]*"))throw new WarehouseException("INVALID_WAREHOUSE_CODE","Invalid code");return v;}static String req(String s,int max){if(s==null||s.trim().isEmpty()||s.trim().length()>max)throw new WarehouseException("INVALID_INPUT","Required value invalid");return s.trim();}
}
