package io.invenlio.warehouse;
import io.swagger.v3.oas.annotations.*;import io.swagger.v3.oas.annotations.media.Schema;import io.swagger.v3.oas.annotations.responses.ApiResponse;import io.swagger.v3.oas.annotations.security.SecurityRequirement;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.time.Instant;import java.util.*;import org.springframework.data.domain.Page;import org.springframework.http.MediaType;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1") @SecurityRequirement(name="bearerAuth") class WarehouseController{
 private final WarehouseService service;WarehouseController(WarehouseService service){this.service=service;}
 @Operation(summary="Create a warehouse",description="Requires warehouse:create. Failures use RFC 7807.")@ApiResponse(responseCode="200",description="Created")@PostMapping("/warehouses")WView create(@Valid @RequestBody WRequest r){return view(service.create(r.domain()));}
 @Operation(summary="List warehouses",description="Tenant-scoped, paginated search. Sort fields: code,name,status,created,updated.")@GetMapping("/warehouses")Page<WView>list(@RequestParam(required=false)String q,@RequestParam(required=false)String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="name,asc")String sort){return service.list(q,status,page,size,sort).map(WarehouseController::view);}
 @Operation(summary="Get a warehouse")@GetMapping("/warehouses/{id}")WView get(@PathVariable UUID id){return view(service.get(id));}
 @Operation(summary="Update explicit warehouse master-data fields",description="Requires warehouse:update and an optimistic version.")@PatchMapping("/warehouses/{id}")WView update(@PathVariable UUID id,@Valid @RequestBody WRequest r){return view(service.update(id,r.domain(),r.version));}
 @Operation(summary="Apply a warehouse lifecycle transition",description="Activate/deactivate require warehouse:update; archive requires warehouse:archive.")@PostMapping("/warehouses/{id}/{action:activate|deactivate|archive}")WView life(@PathVariable UUID id,@PathVariable String action,@Valid @RequestBody Version r){Warehouse.Status next=switch(action){case "activate"->Warehouse.Status.ACTIVE;case "deactivate"->Warehouse.Status.INACTIVE;case "archive"->Warehouse.Status.ARCHIVED;default->throw new IllegalArgumentException("Unsupported warehouse action");};return view(service.transition(id,next,r.version));}
 @Operation(summary="Create a zone",description="Requires warehouse-location:manage.")@PostMapping("/warehouses/{id}/zones")ZView createZone(@PathVariable UUID id,@Valid @RequestBody ZRequest r){return view(service.zone(id,r.domain()));}
 @Operation(summary="List warehouse zones",description="Warehouse-scoped and paginated. Filters: type/status. Sort: code,name,type,status,sequence,created,updated.")@GetMapping("/warehouses/{id}/zones")Page<ZView>zones(@PathVariable UUID id,@RequestParam(required=false)String type,@RequestParam(required=false)String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="sequence,asc")String sort){return service.zones(id,type,status,page,size,sort).map(WarehouseController::view);}
 @Operation(summary="Get a zone")@GetMapping("/warehouse-zones/{id}")ZView zone(@PathVariable UUID id){return view(service.getZone(id));}
 @Operation(summary="Update explicit zone fields",description="Warehouse ownership cannot be changed.")@PatchMapping("/warehouse-zones/{id}")ZView updateZone(@PathVariable UUID id,@Valid @RequestBody ZUpdate r){return view(service.updateZone(id,r.domain(),r.version));}
 @Operation(summary="Archive a zone",description="Rejected while it contains non-archived locations.")@PostMapping("/warehouse-zones/{id}/archive")ZView archiveZone(@PathVariable UUID id,@Valid @RequestBody Version r){return view(service.archiveZone(id,r.version));}
 @Operation(summary="Create a physical location",description="Code and scan code are stable; tenant and warehouse come only from authenticated/path context.")@PostMapping("/warehouses/{id}/locations")LView createLocation(@PathVariable UUID id,@Valid @RequestBody LRequest r){return view(service.location(id,r.domain()));}
 @Operation(summary="List locations",description="Warehouse-scoped and paginated. Filters: zoneId,parentId,type,status,code,q. Sorting is allow-listed.")@GetMapping("/warehouses/{id}/locations")Page<LView>locations(@PathVariable UUID id,@RequestParam(required=false)UUID zoneId,@RequestParam(required=false)UUID parentId,@RequestParam(required=false)String type,@RequestParam(required=false)String status,@RequestParam(required=false)String code,@RequestParam(required=false)String q,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="sequence,asc")String sort){return service.locations(id,zoneId,parentId,type,status,code,q,page,size,sort).map(WarehouseController::view);}
 @Operation(summary="Get a location")@GetMapping("/warehouse-locations/{id}")LView location(@PathVariable UUID id){return view(service.getLocation(id));}
 @Operation(summary="Update explicit mutable location fields",description="Code, scan identity, warehouse, parent, tenant, status and id cannot be mass-assigned.")@PatchMapping("/warehouse-locations/{id}")LView updateLocation(@PathVariable UUID id,@Valid @RequestBody LUpdate r){return view(service.updateLocation(id,r.domain()));}
 @Operation(summary="Move a location",description="Validates same tenant, warehouse and zone and prevents self/direct/multi-level cycles.")@PostMapping("/warehouse-locations/{id}/move")LView move(@PathVariable UUID id,@Valid @RequestBody Move r){return view(service.move(id,r.newParentId,r.version));}
 @Operation(summary="Change location lifecycle",description="Supports block, unblock and archive. Archival is rejected while children remain non-archived.")@PostMapping("/warehouse-locations/{id}/{action:block|unblock|archive}")LView locationLife(@PathVariable UUID id,@PathVariable String action,@Valid @RequestBody Version r){return view(service.status(id,action.toUpperCase(),r.version));}
 @Operation(summary="Resolve an exact location scan code",description="Tenant-scoped exact lookup; another tenant's code returns not found.")@GetMapping("/warehouse-locations/lookup")LView lookup(@RequestParam @NotBlank String scanCode){return view(service.lookup(scanCode));}
 @Operation(summary="Retrieve a flat warehouse topology",description="Sequence/code ordered, non-recursive projection capped at 20,000 locations.")@GetMapping("/warehouses/{id}/topology")List<LView>topology(@PathVariable UUID id){return service.topology(id).stream().map(WarehouseController::view).toList();}
 @Operation(summary="Assign an operational default",description="Purpose is allow-listed and the active compatible location must belong to this warehouse.")@PutMapping("/warehouses/{id}/defaults/{purpose}")void defaultLocation(@PathVariable UUID id,@PathVariable String purpose,@Valid @RequestBody DefaultLocation r){service.assignDefault(id,purpose.toUpperCase(),r.locationId);}
 static WView view(Warehouse w){return new WView(w.id,w.code,w.name,w.status.name(),w.timezone,w.line1,w.line2,w.postal,w.city,w.region,w.country,w.created,w.updated,w.version);}static ZView view(WarehouseZone z){return new ZView(z.id,z.warehouseId,z.code,z.name,z.type.name(),z.status.name(),z.sequence,z.created,z.updated,z.version);}static LView view(StorageLocation l){return new LView(l.id,l.warehouseId,l.zoneId,l.parentId,l.code,l.name,l.type.name(),l.status.name(),l.sequence,l.scanCode,l.maxWeight,l.maxVolume,l.maxPallets,l.length,l.width,l.height,l.created,l.updated,l.version);}
 record WRequest(@NotBlank @Size(max=40)String code,@NotBlank @Size(max=160)String name,@NotBlank @Size(max=64)String timezone,@Size(max=200)String line1,@Size(max=200)String line2,@Size(max=24)String postal,@Size(max=120)String city,@Size(max=120)String region,@Pattern(regexp="(?i)^[A-Z]{2}$")String country,long version){WarehouseService.WarehouseRequest domain(){return new WarehouseService.WarehouseRequest(code,name,timezone,line1,line2,postal,city,region,country);}}
 record ZRequest(@NotBlank @Size(max=40)String code,@NotBlank @Size(max=120)String name,@NotBlank String type,@PositiveOrZero int sequence){WarehouseService.ZoneRequest domain(){return new WarehouseService.ZoneRequest(code,name,type,sequence);}}record ZUpdate(@NotBlank @Size(max=40)String code,@NotBlank @Size(max=120)String name,@NotBlank String type,@PositiveOrZero int sequence,@PositiveOrZero long version){WarehouseService.ZoneRequest domain(){return new WarehouseService.ZoneRequest(code,name,type,sequence);}}
 record LRequest(@NotNull UUID zoneId,UUID parentId,@NotBlank @Size(max=80)String code,@Size(max=160)String name,@NotBlank String type,@PositiveOrZero int sequence,@NotBlank @Size(max=128)String scanCode,@PositiveOrZero Long maxWeightGrams,@PositiveOrZero Long maxVolumeCubicMm,@PositiveOrZero Integer maxPallets,@PositiveOrZero Long lengthMm,@PositiveOrZero Long widthMm,@PositiveOrZero Long heightMm){WarehouseService.LocationRequest domain(){return new WarehouseService.LocationRequest(zoneId,parentId,code,name,type,sequence,scanCode,maxWeightGrams,maxVolumeCubicMm,maxPallets,lengthMm,widthMm,heightMm);}}
 record LUpdate(@NotNull UUID zoneId,@Size(max=160)String name,@NotBlank String type,@PositiveOrZero int sequence,@PositiveOrZero Long maxWeightGrams,@PositiveOrZero Long maxVolumeCubicMm,@PositiveOrZero Integer maxPallets,@PositiveOrZero Long lengthMm,@PositiveOrZero Long widthMm,@PositiveOrZero Long heightMm,@PositiveOrZero long version){WarehouseService.LocationUpdate domain(){return new WarehouseService.LocationUpdate(zoneId,name,type,sequence,maxWeightGrams,maxVolumeCubicMm,maxPallets,lengthMm,widthMm,heightMm,version);}}
 record Version(@PositiveOrZero long version){}record Move(UUID newParentId,@PositiveOrZero long version){}record DefaultLocation(@NotNull UUID locationId){}
 @Schema(description="Warehouse response")record WView(UUID id,String code,String name,String status,String timezone,String addressLine1,String addressLine2,String postalCode,String city,String stateRegion,String countryCode,Instant createdAt,Instant updatedAt,long version){}record ZView(UUID id,UUID warehouseId,String code,String name,String type,String status,int sequence,Instant createdAt,Instant updatedAt,long version){}record LView(UUID id,UUID warehouseId,UUID zoneId,UUID parentId,String code,String name,String type,String status,int sequence,String scanCode,Long maxWeightGrams,Long maxVolumeCubicMm,Integer maxPallets,Long lengthMm,Long widthMm,Long heightMm,Instant createdAt,Instant updatedAt,long version){}
}
