package io.invenlio.catalog;
import java.time.Instant;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.testcontainers.service.connection.ServiceConnection;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.MockMvc;import org.testcontainers.junit.jupiter.*;import org.testcontainers.postgresql.PostgreSQLContainer;
import static org.junit.jupiter.api.Assertions.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@Testcontainers @SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") class CatalogSecurityIntegrationTest {
 static final UUID A=UUID.fromString("11111111-1111-4111-8111-111111111111"),B=UUID.fromString("22222222-2222-4222-8222-222222222222"),USER=UUID.fromString("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),PA=UUID.fromString("10000000-0000-4000-8000-000000000001"),PB=UUID.fromString("20000000-0000-4000-8000-000000000001"),VA=UUID.fromString("10000000-0000-4000-8000-000000000002"),VB=UUID.fromString("20000000-0000-4000-8000-000000000002"),CB=UUID.fromString("20000000-0000-4000-8000-000000000003");
 @Container @ServiceConnection static final PostgreSQLContainer POSTGRES=new PostgreSQLContainer("postgres:17.6-alpine");@Autowired JdbcTemplate db;@Autowired MockMvc mvc;
 @BeforeEach void seed(){db.update("DELETE FROM catalog_barcodes");db.update("DELETE FROM catalog_variant_option_selections");db.update("DELETE FROM catalog_product_option_values");db.update("DELETE FROM catalog_product_options");db.update("DELETE FROM catalog_product_variants");db.update("DELETE FROM catalog_products");db.update("DELETE FROM catalog_categories");db.update("DELETE FROM catalog_brands");db.update("DELETE FROM audit_events");db.update("DELETE FROM membership_roles");db.update("DELETE FROM role_permissions");db.update("DELETE FROM organization_memberships");db.update("DELETE FROM roles");db.update("DELETE FROM user_identities");db.update("DELETE FROM organizations");org(A,"a");org(B,"b");db.update("INSERT INTO user_identities(id,keycloak_subject,status,created_at,updated_at) VALUES (?,?,'ACTIVE',now(),now())",USER,"user-a");var membership=UUID.randomUUID();var role=UUID.randomUUID();db.update("INSERT INTO organization_memberships(id,tenant_id,user_identity_id,status,created_at,updated_at,version) VALUES (?,?,?,'ACTIVE',now(),now(),0)",membership,A,USER);db.update("INSERT INTO roles(id,tenant_id,name,system_role,created_at,updated_at,version) VALUES (?,?,?,false,now(),now(),0)",role,A,"CATALOG_TEST");for(String p:List.of("catalog:read","catalog:update","catalog:create","catalog:archive","catalog-category:manage","catalog-brand:manage"))db.update("INSERT INTO role_permissions VALUES (?,?,?)",A,role,p);db.update("INSERT INTO membership_roles VALUES (?,?,?)",A,membership,role);product(A,PA,VA,"A-SKU");product(B,PB,VB,"B-SKU");db.update("INSERT INTO catalog_barcodes(id,tenant_id,variant_id,type,value,normalized_value,primary_barcode,active,created_at) VALUES (?,?,?,'GTIN_13','4006381333931','4006381333931',true,true,now())",CB,B,VB);}
 @Test void tenantCanReadOwnButNotOtherProductOrVariant()throws Exception{mvc.perform(get("/api/v1/products/"+PA).with(token(A))).andExpect(status().isOk());mvc.perform(get("/api/v1/products/"+PB).with(token(A))).andExpect(status().isNotFound());mvc.perform(get("/api/v1/variants/"+VB).with(token(A))).andExpect(status().isNotFound());}
 @Test void crossTenantBarcodeLookupDoesNotLeak()throws Exception{mvc.perform(get("/api/v1/catalog/lookup?barcode=4006381333931").with(token(A))).andExpect(status().isNotFound());}
 @Test void crossTenantCategoryReferenceRejected()throws Exception{mvc.perform(post("/api/v1/products").with(token(A)).contentType("application/json").content("{\"name\":\"X\",\"categoryId\":\""+UUID.fromString("20000000-0000-4000-8000-000000000004")+"\",\"baseUnit\":\"EA\",\"initialVariant\":{\"sku\":\"X-1\",\"version\":0}}" )).andExpect(status().isNotFound());}
 @Test void staleProductUpdateConflicts()throws Exception{mvc.perform(patch("/api/v1/products/"+PA).with(token(A)).contentType("application/json").content("{\"name\":\"Changed\",\"version\":99}" )).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CONCURRENT_MODIFICATION"));}
 @Test void databaseEnforcesTenantSkuAndBarcodeUniqueness(){assertThrows(DataIntegrityViolationException.class,()->product(A,UUID.randomUUID(),UUID.randomUUID(),"a-sku"));assertDoesNotThrow(()->product(B,UUID.randomUUID(),UUID.randomUUID(),"A-SKU"));assertThrows(DataIntegrityViolationException.class,()->db.update("INSERT INTO catalog_barcodes(id,tenant_id,variant_id,type,value,normalized_value,primary_barcode,active,created_at) VALUES (?,?,?,'INTERNAL','4006381333931','4006381333931',false,true,now())",UUID.randomUUID(),B,VB));}
 @Test void databaseEnforcesSinglePrimaryBarcode(){assertThrows(DataIntegrityViolationException.class,()->db.update("INSERT INTO catalog_barcodes(id,tenant_id,variant_id,type,value,normalized_value,primary_barcode,active,created_at) VALUES (?,?,?,'INTERNAL','SECOND','SECOND',true,true,now())",UUID.randomUUID(),B,VB));}
 private org.springframework.test.web.servlet.request.RequestPostProcessor token(UUID tenant){return jwt().jwt(j->j.subject("user-a").claim("tenant_id",tenant.toString()));}private void org(UUID id,String slug){db.update("INSERT INTO organizations(id,name,slug,status,default_locale,default_timezone,default_currency,created_at,updated_at,version) VALUES (?,?,?,'ACTIVE','en','UTC','EUR',now(),now(),0)",id,slug,slug);if(id.equals(B))db.update("INSERT INTO catalog_categories(id,tenant_id,name,slug,normalized_name,status,created_at,updated_at,version) VALUES (?,?,?,?,?,'ACTIVE',now(),now(),0)",UUID.fromString("20000000-0000-4000-8000-000000000004"),B,"B Category","b-category","B CATEGORY");}private void product(UUID tenant,UUID product,UUID variant,String sku){db.update("INSERT INTO catalog_products(id,tenant_id,name,status,base_unit,created_at,updated_at,version) VALUES (?,?,'Product','DRAFT','EA',now(),now(),0)",product,tenant);db.update("INSERT INTO catalog_product_variants(id,tenant_id,product_id,sku,normalized_sku,status,base_unit,option_signature,created_at,updated_at,version) VALUES (?,?,?,?,?,'DRAFT','EA','DEFAULT',now(),now(),0)",variant,tenant,product,sku,sku.toUpperCase());}
}
