package io.invenlio.sales;import io.invenlio.organization.*;import java.util.*;import org.springframework.context.ApplicationEventPublisher;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service class CustomerService{private final AuthorizationService auth;private final AuditTrail audit;private final JdbcTemplate db;private final ApplicationEventPublisher events;CustomerService(AuthorizationService a,AuditTrail t,JdbcTemplate d,ApplicationEventPublisher e){auth=a;audit=t;db=d;events=e;}
 @Transactional View create(Command c){var a=auth.require(Permission.CUSTOMER_MANAGE);valid(c);String n=number(a.tenantId());UUID id=UUID.randomUUID();db.update("INSERT INTO customers(id,tenant_id,customer_number,name,legal_name,status,email,phone,default_currency,shipping_address,billing_address,created_at,updated_at,version)VALUES(?,?,?,?,?,'DRAFT',?,?,?,?,?,now(),now(),0)",id,a.tenantId(),n,c.name.trim(),blank(c.legalName),blank(c.email),blank(c.phone),currency(c.currency),c.shippingAddress.trim(),blank(c.billingAddress));audit.record(a,"CUSTOMER_CREATED","customer",id.toString());events.publishEvent(new SalesEvents.CustomerCreated(a.tenantId(),id));return get0(a.tenantId(),id);}
 @Transactional(readOnly=true)View get(UUID id){var a=auth.require(Permission.CUSTOMER_READ);return get0(a.tenantId(),id);}
 @Transactional(readOnly=true)List<View>list(String number,String status,String q,int page,int size,String sort){var a=auth.require(Permission.CUSTOMER_READ);page(page,size);String order=switch(sort==null?"createdAt":sort){case"name"->"name";case"number"->"customer_number";case"status"->"status";case"createdAt"->"created_at DESC";case"updatedAt"->"updated_at DESC";default->throw err("INVALID_SORT","Unsupported sort");};String like=q==null?null:"%"+q.trim().toLowerCase()+"%";return db.query("SELECT id FROM customers WHERE tenant_id=? AND(?::text IS NULL OR customer_number=?::text)AND(?::text IS NULL OR status=?::text)AND(?::text IS NULL OR lower(name||' '||customer_number||' '||coalesce(legal_name,'')) LIKE ?::text)ORDER BY "+order+",id OFFSET ? LIMIT ?",(r,n)->get0(a.tenantId(),(UUID)r.getObject(1)),a.tenantId(),number,number,status,status,like,like,page*size,size);}
 @Transactional View update(UUID id,Command c,long version){var a=auth.require(Permission.CUSTOMER_MANAGE);valid(c);int n=db.update("UPDATE customers SET name=?,legal_name=?,email=?,phone=?,default_currency=?,shipping_address=?,billing_address=?,updated_at=now(),version=version+1 WHERE tenant_id=? AND id=? AND version=? AND status<>'ARCHIVED'",c.name.trim(),blank(c.legalName),blank(c.email),blank(c.phone),currency(c.currency),c.shippingAddress.trim(),blank(c.billingAddress),a.tenantId(),id,version);if(n!=1)throw err("CONCURRENT_MODIFICATION","Customer changed or is archived");audit.record(a,"CUSTOMER_UPDATED","customer",id.toString());return get0(a.tenantId(),id);}
 @Transactional View lifecycle(UUID id,String target,long version){var a=auth.require(Permission.CUSTOMER_MANAGE);View v=get0(a.tenantId(),id);boolean ok=switch(target){case"ACTIVE"->Set.of("DRAFT","INACTIVE").contains(v.status);case"INACTIVE"->v.status.equals("ACTIVE");case"BLOCKED"->Set.of("ACTIVE","INACTIVE").contains(v.status);case"ARCHIVED"->Set.of("DRAFT","INACTIVE","BLOCKED").contains(v.status);default->false;};if(!ok)throw err("INVALID_CUSTOMER_TRANSITION","Invalid customer lifecycle transition");if(db.update("UPDATE customers SET status=?,updated_at=now(),version=version+1 WHERE tenant_id=? AND id=? AND version=?",target,a.tenantId(),id,version)!=1)throw err("CONCURRENT_MODIFICATION","Customer changed");audit.record(a,"CUSTOMER_"+target,"customer",id.toString());return get0(a.tenantId(),id);}
 private View get0(UUID t,UUID id){var x=db.query("SELECT id,customer_number,name,legal_name,status,email,phone,default_currency,shipping_address,billing_address,created_at,updated_at,version FROM customers WHERE tenant_id=? AND id=?",(r,n)->new View((UUID)r.getObject(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10),r.getTimestamp(11).toInstant(),r.getTimestamp(12).toInstant(),r.getLong(13)),t,id);if(x.isEmpty())throw err("CUSTOMER_NOT_FOUND","Customer not found");return x.getFirst();}
 private String number(UUID t){return db.queryForObject("INSERT INTO customer_number_counters(tenant_id,next_value)VALUES(?,2)ON CONFLICT(tenant_id)DO UPDATE SET next_value=customer_number_counters.next_value+1 RETURNING next_value-1",Long.class,t).toString().transform(x->"CUS-"+"0".repeat(Math.max(0,6-x.length()))+x);}private static void valid(Command c){if(c==null||c.name==null||c.name.isBlank()||c.name.length()>200||c.shippingAddress==null||c.shippingAddress.isBlank()||c.shippingAddress.length()>1000)throw err("INVALID_CUSTOMER","Name and shipping address are required");currency(c.currency);}private static String currency(String c){try{return Currency.getInstance(c==null?"":c.trim().toUpperCase()).getCurrencyCode();}catch(Exception e){throw err("INVALID_CURRENCY","ISO 4217 currency required");}}private static String blank(String s){return s==null||s.isBlank()?null:s.trim();}private static void page(int p,int s){if(p<0||s<1||s>100)throw err("INVALID_PAGINATION","Invalid pagination");}private static SalesException err(String c,String m){return new SalesException(c,m);}
 record Command(String name,String legalName,String email,String phone,String currency,String shippingAddress,String billingAddress){}record View(UUID id,String customerNumber,String name,String legalName,String status,String email,String phone,String defaultCurrency,String shippingAddress,String billingAddress,java.time.Instant createdAt,java.time.Instant updatedAt,long version){}
}
