package io.invenlio.organization;
import java.time.*; import java.util.*; import org.slf4j.MDC; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.data.domain.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class OrganizationAdministrationService {
 private final AuthorizationService auth; private final OrganizationRepository orgs; private final MembershipRepository members; private final RoleRepository roles; private final AuditRepository audits; private final JdbcTemplate jdbc;
 OrganizationAdministrationService(AuthorizationService a,OrganizationRepository o,MembershipRepository m,RoleRepository r,AuditRepository au,JdbcTemplate j){auth=a;orgs=o;members=m;roles=r;audits=au;jdbc=j;}
 @Transactional(readOnly=true) public Organization current(){var a=auth.require(Permission.ORGANIZATION_READ);return orgs.findByIdAndStatus(a.tenantId(),Organization.Status.ACTIVE).orElseThrow(()->new AccessDeniedException("Organization access denied"));}
 @Transactional public Organization update(String name,String legal,String locale,String timezone,String currency,long version){var a=auth.require(Permission.ORGANIZATION_UPDATE);var o=orgs.findByIdAndStatus(a.tenantId(),Organization.Status.ACTIVE).orElseThrow();if(o.version()!=version)throw new StaleStateException();o.update(name,legal,locale,timezone,currency);audit(a,"organization.updated","organization",o.id().toString());return o;}
 @Transactional(readOnly=true) public Page<OrganizationMembership> members(Pageable p){var a=auth.require(Permission.MEMBER_READ);return members.findAllByTenantId(a.tenantId(),p);}
 @Transactional public OrganizationMembership invite(UUID userId){var a=auth.require(Permission.MEMBER_INVITE);try{var m=members.save(new OrganizationMembership(UUID.randomUUID(),a.tenantId(),userId,OrganizationMembership.Status.INVITED));audit(a,"membership.created","membership",m.id().toString());return m;}catch(DataIntegrityViolationException e){throw new InvalidOperationException("Membership already exists");}}
 @Transactional public OrganizationMembership changeMember(UUID id,String status,long version){var a=auth.require(Permission.MEMBER_UPDATE);var m=members.findByIdAndTenantId(id,a.tenantId()).orElseThrow(()->new NotFoundException("Membership not found"));if(m.version()!=version)throw new StaleStateException();m.transition(OrganizationMembership.Status.valueOf(status));audit(a,"membership.status_changed","membership",id.toString());return m;}
 @Transactional(readOnly=true) public List<Role> roles(){var a=auth.require(Permission.ROLE_READ);return roles.findAllByTenantId(a.tenantId());}
 @Transactional public Role createRole(String name,Set<String> permissions){var a=auth.require(Permission.ROLE_CREATE);var allowed=Arrays.stream(Permission.values()).map(Permission::key).collect(java.util.stream.Collectors.toSet());if(!allowed.containsAll(permissions))throw new InvalidOperationException("Unknown permission");var role=roles.save(new Role(UUID.randomUUID(),a.tenantId(),name,false));permissions.forEach(p->jdbc.update("INSERT INTO role_permissions(tenant_id,role_id,permission_key) VALUES (?,?,?)",a.tenantId(),role.id(),p));audit(a,"role.created","role",role.id().toString());return role;}
 @Transactional public void assign(UUID memberId,UUID roleId){var a=auth.require(Permission.ROLE_ASSIGN);members.findByIdAndTenantId(memberId,a.tenantId()).orElseThrow(()->new NotFoundException("Membership not found"));roles.findByIdAndTenantId(roleId,a.tenantId()).orElseThrow(()->new NotFoundException("Role not found"));jdbc.update("INSERT INTO membership_roles(tenant_id,membership_id,role_id) VALUES (?,?,?) ON CONFLICT DO NOTHING",a.tenantId(),memberId,roleId);audit(a,"role.assigned","membership",memberId.toString());}
 @Transactional(readOnly=true) public Page<AuditEvent> audit(Pageable p,Instant from,Instant to){var a=auth.require(Permission.AUDIT_READ);return audits.findAllByTenantIdAndOccurredAtBetween(a.tenantId(),from,to,p);}
 private void audit(AuthorizationService.Access a,String action,String type,String id){audits.save(new AuditEvent(a.tenantId(),a.subject(),action,type,id,MDC.get("correlationId")));}
}
