package io.invenlio.receiving;import io.swagger.v3.oas.annotations.Operation;import io.swagger.v3.oas.annotations.security.SecurityRequirement;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.time.LocalDate;import java.util.*;import org.springframework.web.bind.annotation.*;
@RestController@RequestMapping("/api/v1")@SecurityRequirement(name="bearerAuth")class ReceivingController{private final ReceivingService service;ReceivingController(ReceivingService s){service=s;}
 @Operation(summary="Create a draft goods receipt",description="Creates tenant-scoped receipt lines for one receiving-eligible purchase order; inventory is unchanged until posting.")@PostMapping("/goods-receipts")ReceivingService.Receipt create(@Valid@RequestBody ReceiptCreate r){return service.create(new ReceivingService.Create(r.purchaseOrderId,r.note,r.lines.stream().map(x->new ReceivingService.Line(x.purchaseOrderLineId,x.receivedBaseQuantity,x.receivingLocationId,x.lotId,x.serialId)).toList()));}
 @Operation(summary="List goods receipts",description="Tenant-scoped filters with bounded pagination and allow-listed sorting.")@GetMapping("/goods-receipts")List<ReceivingService.Receipt> list(@RequestParam(required=false)String receiptNumber,@RequestParam(required=false)UUID purchaseOrderId,@RequestParam(required=false)UUID supplierId,@RequestParam(required=false)UUID warehouseId,@RequestParam(required=false)String status,@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String sort){return service.list(receiptNumber,purchaseOrderId,supplierId,warehouseId,status,from,to,page,size,sort);}@GetMapping("/goods-receipts/{id}")ReceivingService.Receipt get(@PathVariable UUID id){return service.get(id);}
 @Operation(summary="Post a goods receipt",description="Atomically posts physical GOODS_RECEIPT inventory and advances purchase-order receipt progress. Requires Idempotency-Key.")@PostMapping("/goods-receipts/{id}/post")ReceivingService.Receipt post(@PathVariable UUID id,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody Version r){return service.post(id,key,r.version);}
 @Operation(summary="Create a put-away task",description="Allocates part or all of a posted receipt line from its receiving location to one active storage location.")@PostMapping("/put-away-tasks")ReceivingService.Task createTask(@Valid@RequestBody PutAwayCreate r){return service.createTask(new ReceivingService.TaskCreate(r.receiptLineId,r.destinationLocationId,r.quantity));}@GetMapping("/put-away-tasks")List<ReceivingService.Task> tasks(@RequestParam(required=false)UUID receiptId,@RequestParam(required=false)UUID warehouseId,@RequestParam(required=false)UUID sourceLocationId,@RequestParam(required=false)UUID destinationLocationId,@RequestParam(required=false)String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return service.tasks(receiptId,warehouseId,sourceLocationId,destinationLocationId,status,page,size);}@GetMapping("/put-away-tasks/{id}")ReceivingService.Task task(@PathVariable UUID id){return service.getTask(id);}
 @Operation(summary="Complete a put-away task",description="Atomically relocates inventory with paired immutable PUT_AWAY ledger entries. Requires Idempotency-Key.")@PostMapping("/put-away-tasks/{id}/complete")ReceivingService.Task complete(@PathVariable UUID id,@RequestHeader("Idempotency-Key")String key,@Valid@RequestBody Version r){return service.complete(id,key,r.version);}
 record ReceiptCreate(@NotNull UUID purchaseOrderId,@Size(max=1000)String note,@NotEmpty List<@Valid ReceiptLine> lines){}record ReceiptLine(@NotNull UUID purchaseOrderLineId,@NotBlank String receivedBaseQuantity,@NotNull UUID receivingLocationId,UUID lotId,UUID serialId){}record PutAwayCreate(@NotNull UUID receiptLineId,@NotNull UUID destinationLocationId,@NotBlank String quantity){}record Version(@PositiveOrZero long version){}
}
