ALTER TABLE purchase_orders DROP CONSTRAINT purchase_orders_status_check;
ALTER TABLE purchase_orders ALTER COLUMN status TYPE VARCHAR(24);
ALTER TABLE purchase_orders ADD CONSTRAINT purchase_orders_status_check CHECK(status IN('DRAFT','SUBMITTED','APPROVED','SENT','PARTIALLY_RECEIVED','RECEIVED','CANCELLED'));
ALTER TABLE purchase_order_lines ADD COLUMN received_base_quantity NUMERIC(19,6) NOT NULL DEFAULT 0 CHECK(received_base_quantity>=0 AND received_base_quantity<=base_quantity);

DROP TRIGGER po_line_issued_guard ON purchase_order_lines;
CREATE OR REPLACE FUNCTION prevent_issued_po_line_change() RETURNS trigger LANGUAGE plpgsql AS $$DECLARE s VARCHAR(24);t UUID;p UUID;BEGIN IF TG_OP='INSERT' THEN RETURN NEW;END IF;IF TG_OP='DELETE' THEN t=OLD.tenant_id;p=OLD.purchase_order_id;ELSE t=NEW.tenant_id;p=NEW.purchase_order_id;END IF;SELECT status INTO s FROM purchase_orders WHERE tenant_id=t AND id=p;IF s<>'DRAFT' THEN IF TG_OP='UPDATE' AND NEW.id=OLD.id AND NEW.tenant_id=OLD.tenant_id AND NEW.purchase_order_id=OLD.purchase_order_id AND NEW.supplier_id=OLD.supplier_id AND NEW.supplier_product_id=OLD.supplier_product_id AND NEW.variant_id=OLD.variant_id AND NEW.line_number=OLD.line_number AND NEW.ordered_quantity=OLD.ordered_quantity AND NEW.base_quantity=OLD.base_quantity AND NEW.received_base_quantity>=OLD.received_base_quantity AND NEW.received_base_quantity<=NEW.base_quantity THEN RETURN NEW;END IF;RAISE EXCEPTION 'issued purchase order lines are immutable' USING ERRCODE='55000';END IF;IF TG_OP='DELETE' THEN RETURN OLD;END IF;RETURN NEW;END$$;
CREATE TRIGGER po_line_issued_guard BEFORE INSERT OR UPDATE OR DELETE ON purchase_order_lines FOR EACH ROW EXECUTE FUNCTION prevent_issued_po_line_change();

ALTER TABLE inventory_movements DROP CONSTRAINT inventory_movements_movement_type_check;
ALTER TABLE inventory_movements ADD CONSTRAINT inventory_movements_movement_type_check CHECK(movement_type IN('OPENING_BALANCE','MANUAL_ADJUSTMENT','GOODS_RECEIPT','PUT_AWAY'));
ALTER TABLE inventory_movements DROP CONSTRAINT inventory_movements_reason_code_check;
ALTER TABLE inventory_movements ADD CONSTRAINT inventory_movements_reason_code_check CHECK(reason_code IN('INITIAL_LOAD','MANUAL_CORRECTION','FOUND','DAMAGE','OTHER','GOODS_RECEIPT','PUT_AWAY'));

CREATE TABLE goods_receipt_number_counters(tenant_id UUID NOT NULL REFERENCES organizations(id),receipt_year INTEGER NOT NULL,next_value BIGINT NOT NULL,PRIMARY KEY(tenant_id,receipt_year),CHECK(next_value>0));
CREATE TABLE goods_receipts(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,purchase_order_id UUID NOT NULL,supplier_id UUID NOT NULL,warehouse_id UUID NOT NULL,receipt_number VARCHAR(32) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',received_at TIMESTAMPTZ,received_by UUID,note VARCHAR(1000),post_idempotency_key VARCHAR(128),post_fingerprint CHAR(64),created_by UUID NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,version BIGINT NOT NULL DEFAULT 0,UNIQUE(tenant_id,id),UNIQUE(tenant_id,receipt_number),UNIQUE(tenant_id,post_idempotency_key),FOREIGN KEY(tenant_id,purchase_order_id,supplier_id) REFERENCES purchase_orders(tenant_id,id,supplier_id),FOREIGN KEY(tenant_id,warehouse_id) REFERENCES warehouses(tenant_id,id),CHECK(status IN('DRAFT','POSTED','CANCELLED')));
CREATE TABLE goods_receipt_lines(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,goods_receipt_id UUID NOT NULL,purchase_order_id UUID NOT NULL,purchase_order_line_id UUID NOT NULL,variant_id UUID NOT NULL,warehouse_id UUID NOT NULL,receiving_location_id UUID NOT NULL,received_base_quantity NUMERIC(19,6) NOT NULL,unit_code VARCHAR(8) NOT NULL,lot_id UUID,serial_id UUID,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,UNIQUE(tenant_id,goods_receipt_id,id),FOREIGN KEY(tenant_id,goods_receipt_id) REFERENCES goods_receipts(tenant_id,id) ON DELETE CASCADE,FOREIGN KEY(tenant_id,purchase_order_id,purchase_order_line_id) REFERENCES purchase_order_lines(tenant_id,purchase_order_id,id),FOREIGN KEY(tenant_id,variant_id) REFERENCES catalog_product_variants(tenant_id,id),FOREIGN KEY(tenant_id,warehouse_id,receiving_location_id) REFERENCES warehouse_locations(tenant_id,warehouse_id,id),FOREIGN KEY(tenant_id,lot_id) REFERENCES inventory_lots(tenant_id,id),FOREIGN KEY(tenant_id,serial_id) REFERENCES inventory_serials(tenant_id,id),CHECK(received_base_quantity>0));
CREATE TABLE put_away_tasks(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,goods_receipt_id UUID NOT NULL,goods_receipt_line_id UUID NOT NULL,variant_id UUID NOT NULL,warehouse_id UUID NOT NULL,source_location_id UUID NOT NULL,destination_location_id UUID NOT NULL,lot_id UUID,serial_id UUID,quantity NUMERIC(19,6) NOT NULL,unit_code VARCHAR(8) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'PENDING',completed_at TIMESTAMPTZ,completed_by UUID,completion_idempotency_key VARCHAR(128),completion_fingerprint CHAR(64),created_by UUID NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,version BIGINT NOT NULL DEFAULT 0,UNIQUE(tenant_id,id),UNIQUE(tenant_id,completion_idempotency_key),FOREIGN KEY(tenant_id,goods_receipt_id,goods_receipt_line_id) REFERENCES goods_receipt_lines(tenant_id,goods_receipt_id,id),FOREIGN KEY(tenant_id,variant_id) REFERENCES catalog_product_variants(tenant_id,id),FOREIGN KEY(tenant_id,warehouse_id,source_location_id) REFERENCES warehouse_locations(tenant_id,warehouse_id,id),FOREIGN KEY(tenant_id,warehouse_id,destination_location_id) REFERENCES warehouse_locations(tenant_id,warehouse_id,id),CHECK(quantity>0),CHECK(source_location_id<>destination_location_id),CHECK(status IN('PENDING','COMPLETED')));
CREATE INDEX idx_gr_po ON goods_receipts(tenant_id,purchase_order_id);CREATE INDEX idx_gr_supplier ON goods_receipts(tenant_id,supplier_id,status);CREATE INDEX idx_gr_warehouse ON goods_receipts(tenant_id,warehouse_id,status);CREATE INDEX idx_gr_created ON goods_receipts(tenant_id,created_at DESC);CREATE INDEX idx_grl_receipt ON goods_receipt_lines(tenant_id,goods_receipt_id);CREATE INDEX idx_putaway_receipt ON put_away_tasks(tenant_id,goods_receipt_id,status);CREATE INDEX idx_putaway_source ON put_away_tasks(tenant_id,source_location_id,status);CREATE INDEX idx_putaway_destination ON put_away_tasks(tenant_id,destination_location_id,status);

INSERT INTO permissions(permission_key,description) VALUES('receiving:read','Read goods receipts'),('receiving:manage','Manage goods receipts'),('put-away:read','Read put-away tasks'),('put-away:manage','Manage put-away tasks') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(tenant_id,role_id,permission_key) SELECT r.tenant_id,r.id,p.permission_key FROM roles r CROSS JOIN permissions p WHERE r.system_role AND r.name='ORGANIZATION_ADMIN' AND p.permission_key IN('receiving:read','receiving:manage','put-away:read','put-away:manage') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(tenant_id,role_id,permission_key) SELECT r.tenant_id,r.id,p.permission_key FROM roles r CROSS JOIN permissions p WHERE r.system_role AND r.name IN('READ_ONLY','AUDITOR') AND p.permission_key IN('receiving:read','put-away:read') ON CONFLICT DO NOTHING;
