ALTER TABLE inventory_reservations DROP CONSTRAINT inventory_reservations_reference_type_check;
ALTER TABLE inventory_reservations ADD CONSTRAINT inventory_reservations_reference_type_check CHECK(reference_type IN('MANUAL_HOLD','SALES_ORDER_LINE'));

CREATE TABLE customer_number_counters(tenant_id UUID PRIMARY KEY REFERENCES organizations(id),next_value BIGINT NOT NULL CHECK(next_value>0));
CREATE TABLE customers(id UUID PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES organizations(id),customer_number VARCHAR(32) NOT NULL,name VARCHAR(200) NOT NULL,legal_name VARCHAR(200),status VARCHAR(16) NOT NULL,email VARCHAR(254),phone VARCHAR(40),default_currency CHAR(3) NOT NULL,shipping_address VARCHAR(1000) NOT NULL,billing_address VARCHAR(1000),created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,version BIGINT NOT NULL DEFAULT 0,UNIQUE(tenant_id,id),UNIQUE(tenant_id,customer_number),CHECK(status IN('DRAFT','ACTIVE','INACTIVE','BLOCKED','ARCHIVED')),CHECK(default_currency~'^[A-Z]{3}$'));
CREATE TABLE sales_order_number_counters(tenant_id UUID NOT NULL REFERENCES organizations(id),order_year INTEGER NOT NULL,next_value BIGINT NOT NULL CHECK(next_value>0),PRIMARY KEY(tenant_id,order_year));
CREATE TABLE sales_orders(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,customer_id UUID NOT NULL,fulfillment_warehouse_id UUID NOT NULL,sales_order_number VARCHAR(32) NOT NULL,status VARCHAR(24) NOT NULL,currency CHAR(3) NOT NULL,customer_reference VARCHAR(120),requested_delivery_date DATE,shipping_address_snapshot VARCHAR(1000) NOT NULL,billing_address_snapshot VARCHAR(1000),customer_number_snapshot VARCHAR(32) NOT NULL,customer_name_snapshot VARCHAR(200) NOT NULL,warehouse_code_snapshot VARCHAR(40) NOT NULL,warehouse_name_snapshot VARCHAR(160) NOT NULL,subtotal NUMERIC(19,6) NOT NULL DEFAULT 0,created_by UUID NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,version BIGINT NOT NULL DEFAULT 0,cancelled_at TIMESTAMPTZ,cancelled_by UUID,cancellation_reason VARCHAR(500),UNIQUE(tenant_id,id),UNIQUE(tenant_id,sales_order_number),FOREIGN KEY(tenant_id,customer_id)REFERENCES customers(tenant_id,id),FOREIGN KEY(tenant_id,fulfillment_warehouse_id)REFERENCES warehouses(tenant_id,id),CHECK(status IN('DRAFT','CONFIRMED','PARTIALLY_ALLOCATED','ALLOCATED','CANCELLED')),CHECK(currency~'^[A-Z]{3}$'),CHECK(subtotal>=0));
CREATE TABLE sales_order_lines(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,sales_order_id UUID NOT NULL,line_number INTEGER NOT NULL,variant_id UUID NOT NULL,sku_snapshot VARCHAR(128) NOT NULL,description_snapshot VARCHAR(300) NOT NULL,ordered_quantity NUMERIC(19,6) NOT NULL,unit_code VARCHAR(8) NOT NULL,unit_price NUMERIC(19,6) NOT NULL,currency CHAR(3) NOT NULL,line_subtotal NUMERIC(19,6) NOT NULL,allocated_quantity NUMERIC(19,6) NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,version BIGINT NOT NULL DEFAULT 0,UNIQUE(tenant_id,sales_order_id,id),UNIQUE(tenant_id,sales_order_id,line_number),FOREIGN KEY(tenant_id,sales_order_id)REFERENCES sales_orders(tenant_id,id),FOREIGN KEY(tenant_id,variant_id)REFERENCES catalog_product_variants(tenant_id,id),CHECK(line_number>0),CHECK(ordered_quantity>0),CHECK(unit_price>=0),CHECK(line_subtotal=ordered_quantity*unit_price),CHECK(allocated_quantity>=0 AND allocated_quantity<=ordered_quantity),CHECK(currency~'^[A-Z]{3}$'));
CREATE TABLE sales_allocations(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,sales_order_id UUID NOT NULL,sales_order_line_id UUID NOT NULL,inventory_reservation_id UUID NOT NULL,allocated_quantity NUMERIC(19,6) NOT NULL,status VARCHAR(16) NOT NULL,created_at TIMESTAMPTZ NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,inventory_reservation_id),FOREIGN KEY(tenant_id,sales_order_id,sales_order_line_id)REFERENCES sales_order_lines(tenant_id,sales_order_id,id),FOREIGN KEY(tenant_id,inventory_reservation_id)REFERENCES inventory_reservations(tenant_id,id),CHECK(allocated_quantity>0),CHECK(status IN('ACTIVE','RELEASED')));
CREATE INDEX idx_customer_search ON customers(tenant_id,status,name);CREATE INDEX idx_so_status_created ON sales_orders(tenant_id,status,created_at DESC);CREATE INDEX idx_so_customer ON sales_orders(tenant_id,customer_id);CREATE INDEX idx_so_warehouse ON sales_orders(tenant_id,fulfillment_warehouse_id);CREATE INDEX idx_so_delivery ON sales_orders(tenant_id,requested_delivery_date);CREATE INDEX idx_sol_variant ON sales_order_lines(tenant_id,variant_id);CREATE INDEX idx_sa_order ON sales_allocations(tenant_id,sales_order_id,status);
CREATE FUNCTION guard_customer_number()RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF OLD.status<>'DRAFT' AND NEW.customer_number<>OLD.customer_number THEN RAISE EXCEPTION 'active customer number is immutable' USING ERRCODE='55000';END IF;RETURN NEW;END$$;CREATE TRIGGER customer_number_guard BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION guard_customer_number();
CREATE FUNCTION guard_sales_order_lines()RETURNS trigger LANGUAGE plpgsql AS $$DECLARE t UUID;o UUID;s VARCHAR(24);BEGIN IF TG_OP='DELETE' THEN t=OLD.tenant_id;o=OLD.sales_order_id;ELSE t=NEW.tenant_id;o=NEW.sales_order_id;END IF;SELECT status INTO s FROM sales_orders WHERE tenant_id=t AND id=o;IF s<>'DRAFT' THEN IF TG_OP='UPDATE' AND NEW.id=OLD.id AND NEW.tenant_id=OLD.tenant_id AND NEW.sales_order_id=OLD.sales_order_id AND NEW.variant_id=OLD.variant_id AND NEW.sku_snapshot=OLD.sku_snapshot AND NEW.description_snapshot=OLD.description_snapshot AND NEW.ordered_quantity=OLD.ordered_quantity AND NEW.unit_code=OLD.unit_code AND NEW.unit_price=OLD.unit_price AND NEW.currency=OLD.currency AND NEW.line_subtotal=OLD.line_subtotal AND((s<>'CANCELLED' AND NEW.allocated_quantity>=OLD.allocated_quantity)OR(s='CANCELLED' AND NEW.allocated_quantity=0))AND NEW.allocated_quantity<=NEW.ordered_quantity THEN RETURN NEW;END IF;RAISE EXCEPTION 'confirmed sales order lines are commercially immutable' USING ERRCODE='55000';END IF;IF TG_OP='DELETE' THEN RETURN OLD;END IF;RETURN NEW;END$$;CREATE TRIGGER sales_order_line_guard BEFORE INSERT OR UPDATE OR DELETE ON sales_order_lines FOR EACH ROW EXECUTE FUNCTION guard_sales_order_lines();
INSERT INTO permissions(permission_key,description)VALUES('customer:read','Read customers'),('customer:manage','Manage customers'),('sales-order:read','Read sales orders'),('sales-order:manage','Manage sales orders'),('sales-order:allocate','Allocate sales orders')ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(tenant_id,role_id,permission_key)SELECT r.tenant_id,r.id,p.permission_key FROM roles r CROSS JOIN permissions p WHERE r.system_role AND r.name='ORGANIZATION_ADMIN' AND p.permission_key IN('customer:read','customer:manage','sales-order:read','sales-order:manage','sales-order:allocate')ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(tenant_id,role_id,permission_key)SELECT r.tenant_id,r.id,p.permission_key FROM roles r CROSS JOIN permissions p WHERE r.system_role AND r.name IN('READ_ONLY','AUDITOR') AND p.permission_key IN('customer:read','sales-order:read')ON CONFLICT DO NOTHING;
