INSERT INTO permissions(permission_key,description) VALUES ('warehouse:read','Read warehouses'),('warehouse:create','Create warehouses'),('warehouse:update','Update warehouses'),('warehouse:archive','Archive warehouses'),('warehouse-location:read','Read warehouse topology'),('warehouse-location:manage','Manage warehouse topology') ON CONFLICT DO NOTHING;
CREATE TABLE warehouses(id UUID PRIMARY KEY,tenant_id UUID NOT NULL REFERENCES organizations(id),code VARCHAR(40) NOT NULL,normalized_code VARCHAR(40) NOT NULL,name VARCHAR(160) NOT NULL,status VARCHAR(16) NOT NULL,timezone VARCHAR(64) NOT NULL,address_line1 VARCHAR(200),address_line2 VARCHAR(200),postal_code VARCHAR(24),city VARCHAR(120),state_region VARCHAR(120),country_code VARCHAR(2),created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,version BIGINT NOT NULL DEFAULT 0,UNIQUE(tenant_id,id),UNIQUE(tenant_id,normalized_code),CHECK(status IN('DRAFT','ACTIVE','INACTIVE','ARCHIVED')),CHECK(country_code IS NULL OR country_code ~ '^[A-Z]{2}$'));
CREATE INDEX idx_warehouses_tenant_status ON warehouses(tenant_id,status);CREATE INDEX idx_warehouses_tenant_name ON warehouses(tenant_id,lower(name));
CREATE TABLE warehouse_zones(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,warehouse_id UUID NOT NULL,code VARCHAR(40) NOT NULL,normalized_code VARCHAR(40) NOT NULL,name VARCHAR(120) NOT NULL,type VARCHAR(24) NOT NULL,status VARCHAR(16) NOT NULL,sequence INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,version BIGINT NOT NULL DEFAULT 0,UNIQUE(tenant_id,warehouse_id,id),UNIQUE(tenant_id,warehouse_id,normalized_code),FOREIGN KEY(tenant_id,warehouse_id) REFERENCES warehouses(tenant_id,id) ON DELETE RESTRICT,CHECK(type IN('RECEIVING','STORAGE','PICKING','PACKING','SHIPPING','RETURNS','QUARANTINE','DAMAGED','QUALITY_CONTROL','STAGING','TRANSIT')),CHECK(status IN('ACTIVE','INACTIVE','ARCHIVED')));
CREATE TABLE warehouse_locations(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,warehouse_id UUID NOT NULL,zone_id UUID NOT NULL,parent_location_id UUID,code VARCHAR(80) NOT NULL,normalized_code VARCHAR(80) NOT NULL,name VARCHAR(160),type VARCHAR(24) NOT NULL,status VARCHAR(16) NOT NULL,sequence INTEGER NOT NULL DEFAULT 0,scan_code VARCHAR(128) NOT NULL,normalized_scan_code VARCHAR(128) NOT NULL,max_weight_grams BIGINT,max_volume_cubic_mm BIGINT,max_pallets INTEGER,length_mm BIGINT,width_mm BIGINT,height_mm BIGINT,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,version BIGINT NOT NULL DEFAULT 0,UNIQUE(tenant_id,warehouse_id,id),UNIQUE(tenant_id,warehouse_id,normalized_code),UNIQUE(tenant_id,normalized_scan_code),FOREIGN KEY(tenant_id,warehouse_id,zone_id) REFERENCES warehouse_zones(tenant_id,warehouse_id,id) ON DELETE RESTRICT,FOREIGN KEY(tenant_id,warehouse_id,parent_location_id) REFERENCES warehouse_locations(tenant_id,warehouse_id,id) ON DELETE RESTRICT,CHECK(parent_location_id IS NULL OR parent_location_id<>id),CHECK(type IN('AISLE','RACK','SHELF','BIN','FLOOR','PALLET_POSITION','STAGING','RECEIVING','PACKING','SHIPPING','RETURNS','QUARANTINE','DAMAGED')),CHECK(status IN('ACTIVE','BLOCKED','INACTIVE','ARCHIVED')),CHECK(max_weight_grams>=0),CHECK(max_volume_cubic_mm>=0),CHECK(max_pallets>=0),CHECK(length_mm>=0),CHECK(width_mm>=0),CHECK(height_mm>=0));
CREATE INDEX idx_locations_zone ON warehouse_locations(tenant_id,warehouse_id,zone_id);CREATE INDEX idx_locations_parent ON warehouse_locations(tenant_id,warehouse_id,parent_location_id);CREATE INDEX idx_locations_type_status ON warehouse_locations(tenant_id,warehouse_id,type,status);
CREATE TABLE warehouse_operational_locations(tenant_id UUID NOT NULL,warehouse_id UUID NOT NULL,purpose VARCHAR(24) NOT NULL,location_id UUID NOT NULL,PRIMARY KEY(tenant_id,warehouse_id,purpose),FOREIGN KEY(tenant_id,warehouse_id) REFERENCES warehouses(tenant_id,id) ON DELETE RESTRICT,FOREIGN KEY(tenant_id,warehouse_id,location_id) REFERENCES warehouse_locations(tenant_id,warehouse_id,id) ON DELETE RESTRICT,CHECK(purpose IN('RECEIVING','SHIPPING','RETURNS','QUARANTINE','DAMAGED')));
INSERT INTO role_permissions(tenant_id,role_id,permission_key) SELECT r.tenant_id,r.id,p.permission_key FROM roles r CROSS JOIN permissions p WHERE r.system_role AND r.name='ORGANIZATION_ADMIN' AND p.permission_key LIKE 'warehouse%' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(tenant_id,role_id,permission_key) SELECT r.tenant_id,r.id,p.permission_key FROM roles r CROSS JOIN permissions p WHERE r.system_role AND r.name IN('READ_ONLY','AUDITOR') AND p.permission_key IN('warehouse:read','warehouse-location:read') ON CONFLICT DO NOTHING;
