ALTER TABLE catalog_product_variants ADD COLUMN tracking_mode VARCHAR(20) NOT NULL DEFAULT 'NONE', ADD COLUMN expiration_required BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE catalog_product_variants ADD CONSTRAINT ck_variant_tracking_mode CHECK(tracking_mode IN('NONE','LOT','SERIAL','LOT_AND_SERIAL')), ADD CONSTRAINT ck_variant_expiry_policy CHECK(NOT expiration_required OR tracking_mode IN('LOT','LOT_AND_SERIAL'));

INSERT INTO permissions(permission_key,description) VALUES ('inventory-traceability:read','Read lots and serials'),('inventory-traceability:manage','Manage lots and serials') ON CONFLICT DO NOTHING;

CREATE TABLE inventory_lots(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,variant_id UUID NOT NULL,lot_number VARCHAR(128) NOT NULL,normalized_lot_number VARCHAR(128) NOT NULL,manufactured_on DATE,expires_on DATE,status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,version BIGINT NOT NULL DEFAULT 0,UNIQUE(tenant_id,id),UNIQUE(tenant_id,variant_id,id),UNIQUE(tenant_id,variant_id,normalized_lot_number),FOREIGN KEY(tenant_id,variant_id)REFERENCES catalog_product_variants(tenant_id,id)ON DELETE RESTRICT,CHECK(status IN('ACTIVE','BLOCKED','ARCHIVED')),CHECK(expires_on IS NULL OR manufactured_on IS NULL OR expires_on>=manufactured_on));
CREATE TABLE inventory_serials(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,variant_id UUID NOT NULL,serial_number VARCHAR(128) NOT NULL,normalized_serial_number VARCHAR(128) NOT NULL,lot_id UUID,status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,version BIGINT NOT NULL DEFAULT 0,UNIQUE(tenant_id,id),UNIQUE(tenant_id,variant_id,id),UNIQUE(tenant_id,variant_id,normalized_serial_number),FOREIGN KEY(tenant_id,variant_id)REFERENCES catalog_product_variants(tenant_id,id)ON DELETE RESTRICT,FOREIGN KEY(tenant_id,variant_id,lot_id)REFERENCES inventory_lots(tenant_id,variant_id,id)ON DELETE RESTRICT,CHECK(status IN('ACTIVE','BLOCKED','ARCHIVED')));

ALTER TABLE inventory_ledger_entries ADD COLUMN lot_id UUID, ADD COLUMN serial_id UUID;
ALTER TABLE inventory_ledger_entries ADD CONSTRAINT fk_ledger_lot FOREIGN KEY(tenant_id,variant_id,lot_id)REFERENCES inventory_lots(tenant_id,variant_id,id)ON DELETE RESTRICT, ADD CONSTRAINT fk_ledger_serial FOREIGN KEY(tenant_id,variant_id,serial_id)REFERENCES inventory_serials(tenant_id,variant_id,id)ON DELETE RESTRICT;
ALTER TABLE inventory_balances ADD COLUMN lot_id UUID, ADD COLUMN serial_id UUID;
ALTER TABLE inventory_balances DROP CONSTRAINT inventory_balances_tenant_id_variant_id_warehouse_id_locati_key;
ALTER TABLE inventory_balances ADD CONSTRAINT fk_balance_lot FOREIGN KEY(tenant_id,variant_id,lot_id)REFERENCES inventory_lots(tenant_id,variant_id,id)ON DELETE RESTRICT, ADD CONSTRAINT fk_balance_serial FOREIGN KEY(tenant_id,variant_id,serial_id)REFERENCES inventory_serials(tenant_id,variant_id,id)ON DELETE RESTRICT;
CREATE UNIQUE INDEX uq_inventory_balance_dimension ON inventory_balances(tenant_id,variant_id,warehouse_id,location_id,lot_id,serial_id) NULLS NOT DISTINCT;

CREATE INDEX idx_lots_variant_number ON inventory_lots(tenant_id,variant_id,normalized_lot_number);CREATE INDEX idx_lots_variant_expiry ON inventory_lots(tenant_id,variant_id,expires_on);CREATE INDEX idx_lots_status ON inventory_lots(tenant_id,status);
CREATE INDEX idx_serials_variant_number ON inventory_serials(tenant_id,variant_id,normalized_serial_number);CREATE INDEX idx_serials_lot ON inventory_serials(tenant_id,lot_id);CREATE INDEX idx_serials_status ON inventory_serials(tenant_id,status);
CREATE INDEX idx_ledger_lot_time ON inventory_ledger_entries(tenant_id,lot_id,occurred_at DESC);CREATE INDEX idx_ledger_serial_time ON inventory_ledger_entries(tenant_id,serial_id,occurred_at DESC);CREATE INDEX idx_balances_variant_lot ON inventory_balances(tenant_id,variant_id,lot_id);CREATE INDEX idx_balances_serial ON inventory_balances(tenant_id,serial_id);

INSERT INTO role_permissions(tenant_id,role_id,permission_key)SELECT r.tenant_id,r.id,p.permission_key FROM roles r CROSS JOIN permissions p WHERE r.system_role AND r.name='ORGANIZATION_ADMIN' AND p.permission_key LIKE 'inventory-traceability:%' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(tenant_id,role_id,permission_key)SELECT r.tenant_id,r.id,p.permission_key FROM roles r CROSS JOIN permissions p WHERE r.system_role AND r.name IN('READ_ONLY','AUDITOR') AND p.permission_key='inventory-traceability:read' ON CONFLICT DO NOTHING;
