package io.invenlio;
import java.util.UUID; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.testcontainers.service.connection.ServiceConnection; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import org.testcontainers.junit.jupiter.*; import org.testcontainers.postgresql.PostgreSQLContainer;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@Testcontainers @SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") class CrossTenantSecurityIntegrationTest {
 static final UUID TENANT_A=UUID.fromString("11111111-1111-4111-8111-111111111111"),TENANT_B=UUID.fromString("22222222-2222-4222-8222-222222222222");
 @Container @ServiceConnection static final PostgreSQLContainer POSTGRES=new PostgreSQLContainer("postgres:17.6-alpine");
 @Autowired JdbcTemplate db; @Autowired MockMvc mvc;
 @BeforeEach void seed(){db.update("DELETE FROM audit_events");db.update("DELETE FROM membership_roles");db.update("DELETE FROM role_permissions");db.update("DELETE FROM organization_memberships");db.update("DELETE FROM roles");db.update("DELETE FROM user_identities");db.update("DELETE FROM organizations");org(TENANT_A,"tenant-a");org(TENANT_B,"tenant-b");db.update("INSERT INTO user_identities VALUES (?,?,NULL,NULL,'ACTIVE',now(),now())",UUID.fromString("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),"user-a");db.update("INSERT INTO organization_memberships VALUES (?,?,?,'ACTIVE',now(),now(),0)",UUID.fromString("aaaaaaaa-0000-4000-8000-000000000001"),TENANT_A,UUID.fromString("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"));db.update("INSERT INTO roles VALUES (?,?,?,false,now(),now(),0)",UUID.fromString("aaaaaaaa-0000-4000-8000-000000000002"),TENANT_A,"ADMIN");db.update("INSERT INTO role_permissions VALUES (?,?,?)",TENANT_A,UUID.fromString("aaaaaaaa-0000-4000-8000-000000000002"),"organization:read");db.update("INSERT INTO membership_roles VALUES (?,?,?)",TENANT_A,UUID.fromString("aaaaaaaa-0000-4000-8000-000000000001"),UUID.fromString("aaaaaaaa-0000-4000-8000-000000000002"));}
 void org(UUID id,String slug){db.update("INSERT INTO organizations VALUES (?,?,?,NULL,'ACTIVE','en','UTC','EUR',now(),now(),0)",id,slug,slug);}
 @Test void activeMemberCanReadOnlyOwnTenant()throws Exception{mvc.perform(get("/api/v1/organization").with(jwt().jwt(j->j.subject("user-a").claim("tenant_id",TENANT_A.toString())))).andExpect(status().isOk()).andExpect(jsonPath("$.id").value(TENANT_A.toString()));mvc.perform(get("/api/v1/organization").with(jwt().jwt(j->j.subject("user-a").claim("tenant_id",TENANT_B.toString())))).andExpect(status().isForbidden());}
 @Test void malformedTenantAndMissingMembershipFailClosed()throws Exception{mvc.perform(get("/api/v1/organization").with(jwt().jwt(j->j.subject("user-a").claim("tenant_id","not-a-uuid")))).andExpect(status().isForbidden());mvc.perform(get("/api/v1/organization").with(jwt().jwt(j->j.subject("unknown").claim("tenant_id",TENANT_A.toString())))).andExpect(status().isForbidden());}
}
