package io.invenlio.inventory;
import java.math.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service class InventoryReservationAllocationAdapter implements InventoryReservationAllocation{
 private final JdbcTemplate db;InventoryReservationAllocationAdapter(JdbcTemplate d){db=d;}
 @Override@Transactional(readOnly=true)public List<Candidate>candidates(UUID t,UUID v,UUID w,int limit){if(limit<1||limit>1000)throw new IllegalArgumentException("Invalid candidate limit");return db.query("SELECT b.location_id,b.lot_id,b.serial_id,b.on_hand_quantity-b.reserved_quantity,b.unit_code,l.expires_on,l.lot_number,s.serial_number FROM inventory_balances b JOIN catalog_product_variants v ON v.tenant_id=b.tenant_id AND v.id=b.variant_id JOIN warehouses w ON w.tenant_id=b.tenant_id AND w.id=b.warehouse_id JOIN warehouse_locations x ON x.tenant_id=b.tenant_id AND x.warehouse_id=b.warehouse_id AND x.id=b.location_id LEFT JOIN inventory_lots l ON l.tenant_id=b.tenant_id AND l.id=b.lot_id LEFT JOIN inventory_serials s ON s.tenant_id=b.tenant_id AND s.id=b.serial_id WHERE b.tenant_id=? AND b.variant_id=? AND b.warehouse_id=? AND v.status='ACTIVE' AND w.status='ACTIVE' AND x.status='ACTIVE' AND (b.lot_id IS NULL OR(l.status='ACTIVE' AND(l.expires_on IS NULL OR l.expires_on>=current_date))) AND(b.serial_id IS NULL OR s.status='ACTIVE') AND b.on_hand_quantity>b.reserved_quantity ORDER BY l.expires_on ASC NULLS LAST,l.normalized_lot_number NULLS LAST,x.sequence,x.normalized_code,s.normalized_serial_number NULLS LAST,b.id LIMIT ?",(r,n)->new Candidate((UUID)r.getObject(1),(UUID)r.getObject(2),(UUID)r.getObject(3),r.getBigDecimal(4),r.getString(5),r.getDate(6)==null?null:r.getDate(6).toLocalDate(),r.getString(7),r.getString(8)),t,v,w,limit);}
 @Override@Transactional public Optional<Reservation> reserve(UUID t,UUID actor,String key,String ref,UUID v,UUID w,UUID loc,UUID lot,UUID serial,BigDecimal q){if(ref==null||ref.isBlank()||q==null||q.signum()<=0||q.scale()>6)throw new IllegalArgumentException("Invalid sales reservation");lock(t,v,w,loc,lot,serial);List<BigDecimal>won=db.query("UPDATE inventory_balances SET reserved_quantity=reserved_quantity+?,updated_at=now(),version=version+1 WHERE tenant_id=? AND variant_id=? AND warehouse_id=? AND location_id=? AND lot_id IS NOT DISTINCT FROM ? AND serial_id IS NOT DISTINCT FROM ? AND reserved_quantity+?<=on_hand_quantity RETURNING reserved_quantity",(r,n)->r.getBigDecimal(1),q,t,v,w,loc,lot,serial,q);if(won.isEmpty())return Optional.empty();String unit=db.queryForObject("SELECT unit_code FROM inventory_balances WHERE tenant_id=? AND variant_id=? AND warehouse_id=? AND location_id=? AND lot_id IS NOT DISTINCT FROM ? AND serial_id IS NOT DISTINCT FROM ?",String.class,t,v,w,loc,lot,serial);UUID id=UUID.randomUUID();db.update("INSERT INTO inventory_reservations(id,tenant_id,reference_type,reference_id,status,requested_quantity,unit_code,created_at,created_by,updated_at,version,idempotency_key,request_fingerprint)VALUES(?,?, 'SALES_ORDER_LINE',?,'ACTIVE',?,?,now(),?,now(),0,?,repeat(md5(?),2))",id,t,ref,q,unit,actor.toString(),key,key+"|"+ref+"|"+q);db.update("INSERT INTO inventory_reservation_allocations(id,tenant_id,reservation_id,variant_id,warehouse_id,location_id,lot_id,serial_id,quantity,unit_code,created_at)VALUES(?,?,?,?,?,?,?,?,?,?,now())",UUID.randomUUID(),t,id,v,w,loc,lot,serial,q,unit);return Optional.of(new Reservation(id,q,unit));}
 @Override@Transactional public void release(UUID t,UUID actor,UUID id){List<UUID>won=db.query("UPDATE inventory_reservations SET status='RELEASED',updated_at=now(),version=version+1 WHERE tenant_id=? AND id=? AND reference_type='SALES_ORDER_LINE' AND status='ACTIVE' RETURNING id",(r,n)->(UUID)r.getObject(1),t,id);if(won.isEmpty())return;var xs=db.query("SELECT variant_id,warehouse_id,location_id,lot_id,serial_id,quantity FROM inventory_reservation_allocations WHERE tenant_id=? AND reservation_id=?",(r,n)->new Object[]{r.getObject(1),r.getObject(2),r.getObject(3),r.getObject(4),r.getObject(5),r.getBigDecimal(6)},t,id);for(var x:xs){lock(t,(UUID)x[0],(UUID)x[1],(UUID)x[2],(UUID)x[3],(UUID)x[4]);if(db.update("UPDATE inventory_balances SET reserved_quantity=reserved_quantity-?,updated_at=now(),version=version+1 WHERE tenant_id=? AND variant_id=? AND warehouse_id=? AND location_id=? AND lot_id IS NOT DISTINCT FROM ? AND serial_id IS NOT DISTINCT FROM ? AND reserved_quantity>=?",x[5],t,x[0],x[1],x[2],x[3],x[4],x[5])!=1)throw new IllegalStateException("Reservation projection mismatch");}}
 @Override@Transactional(readOnly=true)public BigDecimal activeQuantity(UUID t,UUID id,String ref){List<BigDecimal>q=db.query("SELECT requested_quantity FROM inventory_reservations WHERE tenant_id=? AND id=? AND reference_type='SALES_ORDER_LINE' AND reference_id=? AND status='ACTIVE'",(r,n)->r.getBigDecimal(1),t,id,ref);return q.isEmpty()?BigDecimal.ZERO:q.getFirst();}
 private void lock(UUID t,UUID v,UUID w,UUID l,UUID lot,UUID serial){db.queryForObject("SELECT pg_advisory_xact_lock(hashtextextended(?,0))",Object.class,t+":"+v+":"+w+":"+l+":"+lot+":"+serial);}
}
