package io.invenlio.inventory;
import io.swagger.v3.oas.annotations.*;import io.swagger.v3.oas.annotations.security.SecurityRequirement;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.time.Instant;import java.util.*;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/inventory")@SecurityRequirement(name="bearerAuth")class InventoryController{private final InventoryService service;InventoryController(InventoryService s){service=s;}
 @Operation(summary="Post an immutable manual inventory adjustment",description="Requires inventory:adjust and Idempotency-Key. Lot/serial IDs follow the Catalog tracking-mode matrix.")@PostMapping("/adjustments")InventoryService.AdjustmentResult adjust(@RequestHeader(name="Idempotency-Key",required=false)String key,@Valid @RequestBody AdjustmentRequest r){return service.adjust(key,new InventoryService.Adjustment(r.variantId,r.warehouseId,r.locationId,r.lotId,r.serialId,r.quantityDelta,r.reason,r.note));}
 @Operation(summary="List current on-hand balances",description="Requires inventory:read. This projection is derived from the immutable ledger.")@GetMapping("/balances")List<InventoryService.BalanceView>balances(@RequestParam(required=false)UUID variantId,@RequestParam(required=false)UUID warehouseId,@RequestParam(required=false)UUID locationId,@RequestParam(required=false)Boolean positiveOnly,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String sort){return service.balances(variantId,warehouseId,locationId,positiveOnly,page,size,sort);}
 @Operation(summary="List immutable inventory ledger history",description="Requires inventory-ledger:read. Tenant-scoped filters include lotId and serialId.")@GetMapping("/ledger")List<InventoryService.LedgerView>ledger(@RequestParam(required=false)UUID variantId,@RequestParam(required=false)UUID warehouseId,@RequestParam(required=false)UUID locationId,@RequestParam(required=false)UUID lotId,@RequestParam(required=false)UUID serialId,@RequestParam(required=false)String movementType,@RequestParam(required=false)Instant from,@RequestParam(required=false)Instant to,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String sort){return service.ledger(variantId,warehouseId,locationId,lotId,serialId,movementType,from,to,page,size,sort);}
 @Operation(summary="Get movement and entries")@GetMapping("/movements/{id}")InventoryService.MovementView movement(@PathVariable UUID id){return service.movement(id);}
 record AdjustmentRequest(@NotNull UUID variantId,@NotNull UUID warehouseId,@NotNull UUID locationId,UUID lotId,UUID serialId,@NotBlank String quantityDelta,@NotBlank String reason,@Size(max=500)String note){}
}
