package io.invenlio.inventory;import io.swagger.v3.oas.annotations.Operation;import io.swagger.v3.oas.annotations.security.SecurityRequirement;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.time.LocalDate;import java.util.*;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/inventory")@SecurityRequirement(name="bearerAuth")class TraceabilityController{private final TraceabilityService service;TraceabilityController(TraceabilityService s){service=s;}
 @Operation(summary="Register a lot / batch identity",description="Requires inventory-traceability:manage; registration does not create stock.")@PostMapping("/lots")TraceabilityService.LotView createLot(@Valid@RequestBody LotRequest r){return service.createLot(new TraceabilityService.LotCommand(r.variantId,r.lotNumber,r.manufacturedOn,r.expiresOn));}
 @GetMapping("/lots")List<TraceabilityService.LotView>lots(@RequestParam(required=false)UUID variantId,@RequestParam(required=false)String status,@RequestParam(required=false)String lotNumber,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String sort){return service.lots(variantId,status,lotNumber,page,size,sort);}@GetMapping("/lots/{id}")TraceabilityService.LotView lot(@PathVariable UUID id){return service.getLot(id);}
 @PatchMapping("/lots/{id}")TraceabilityService.LotView updateLot(@PathVariable UUID id,@Valid@RequestBody LotUpdate r){return service.updateLot(id,r.manufacturedOn,r.expiresOn,r.version);}@PostMapping("/lots/{id}/block")TraceabilityService.LotView blockLot(@PathVariable UUID id,@RequestBody Version r){return service.lotStatus(id,"BLOCKED",r.version);}@PostMapping("/lots/{id}/unblock")TraceabilityService.LotView unblockLot(@PathVariable UUID id,@RequestBody Version r){return service.lotStatus(id,"ACTIVE",r.version);}@PostMapping("/lots/{id}/archive")TraceabilityService.LotView archiveLot(@PathVariable UUID id,@RequestBody Version r){return service.lotStatus(id,"ARCHIVED",r.version);}
 @Operation(summary="Register a serial identity",description="Requires inventory-traceability:manage; one serial represents one physical unit.")@PostMapping("/serials")TraceabilityService.SerialView createSerial(@Valid@RequestBody SerialRequest r){return service.createSerial(new TraceabilityService.SerialCommand(r.variantId,r.serialNumber,r.lotId));}
 @GetMapping("/serials")List<TraceabilityService.SerialView>serials(@RequestParam(required=false)UUID variantId,@RequestParam(required=false)UUID lotId,@RequestParam(required=false)String status,@RequestParam(required=false)String serialNumber,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String sort){return service.serials(variantId,lotId,status,serialNumber,page,size,sort);}@GetMapping("/serials/{id}")TraceabilityService.SerialView serial(@PathVariable UUID id){return service.getSerial(id);}@PostMapping("/serials/{id}/block")TraceabilityService.SerialView blockSerial(@PathVariable UUID id,@RequestBody Version r){return service.serialStatus(id,"BLOCKED",r.version);}@PostMapping("/serials/{id}/unblock")TraceabilityService.SerialView unblockSerial(@PathVariable UUID id,@RequestBody Version r){return service.serialStatus(id,"ACTIVE",r.version);}@PostMapping("/serials/{id}/archive")TraceabilityService.SerialView archiveSerial(@PathVariable UUID id,@RequestBody Version r){return service.serialStatus(id,"ARCHIVED",r.version);}
 record LotRequest(@NotNull UUID variantId,@NotBlank@Size(max=128)String lotNumber,LocalDate manufacturedOn,LocalDate expiresOn){}record LotUpdate(LocalDate manufacturedOn,LocalDate expiresOn,@PositiveOrZero long version){}record SerialRequest(@NotNull UUID variantId,@NotBlank@Size(max=128)String serialNumber,UUID lotId){}record Version(@PositiveOrZero long version){}
}
