package io.invenlio.catalog;
import io.invenlio.organization.*; import java.util.*; import org.springframework.context.ApplicationEventPublisher; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service class CatalogService {
 private final AuthorizationService auth;private final AuditTrail audit;private final ProductRepository products;private final VariantRepository variants;private final CategoryRepository categories;private final BrandRepository brands;private final BarcodeRepository barcodes;private final OptionRepository options;private final OptionValueRepository values;private final ApplicationEventPublisher events;
 CatalogService(AuthorizationService a,AuditTrail at,ProductRepository p,VariantRepository v,CategoryRepository c,BrandRepository b,BarcodeRepository bc,OptionRepository o,OptionValueRepository ov,ApplicationEventPublisher e){auth=a;audit=at;products=p;variants=v;categories=c;brands=b;barcodes=bc;options=o;values=ov;events=e;}
 @Transactional Product create(String name,String description,UUID category,UUID brand,String unit,VariantInput initial){var a=auth.require(Permission.CATALOG_CREATE);relations(a.tenantId(),category,brand);var p=products.save(new Product(a.tenantId(),name,description,category,brand,UnitOfMeasure.parse(unit)));if(initial==null)throw new CatalogException("INITIAL_VARIANT_REQUIRED","A simple product requires its initial SKU");var v=variants.save(new ProductVariant(a.tenantId(),p.id(),initial.sku(),initial.displayName(),UnitOfMeasure.parse(unit),initial.weightGrams(),initial.lengthMm(),initial.widthMm(),initial.heightMm(),"DEFAULT"));audit.record(a,"PRODUCT_CREATED","product",p.id().toString());audit.record(a,"VARIANT_CREATED","variant",v.id().toString());events.publishEvent(new CatalogEvents.ProductCreated(a.tenantId(),p.id()));return p;}
 @Transactional(readOnly=true) Product get(UUID id){var a=auth.require(Permission.CATALOG_READ);return product(id,a.tenantId());}
 @Transactional(readOnly=true) Page<Product> search(String q,String status,UUID category,UUID brand,int page,int size,String sort){var a=auth.require(Permission.CATALOG_READ);var safe=sort==null?"name":sort;if(!Set.of("name","createdAt","updatedAt").contains(safe))throw new CatalogException("INVALID_SORT","Unsupported product sort");return products.search(a.tenantId(),blank(q),status==null?null:Product.Status.valueOf(status).name(),category,brand,PageRequest.of(Math.max(page,0),Math.min(Math.max(size,1),100),Sort.by(safe)));}
 @Transactional Product update(UUID id,String name,String description,UUID category,UUID brand,long version){var a=auth.require(Permission.CATALOG_UPDATE);relations(a.tenantId(),category,brand);var p=product(id,a.tenantId());p.update(name,description,category,brand,version);audit.record(a,"PRODUCT_UPDATED","product",id.toString());return p;}
 @Transactional Product transitionProduct(UUID id,Product.Status status,long version){var a=auth.require(status==Product.Status.ARCHIVED?Permission.CATALOG_ARCHIVE:Permission.CATALOG_UPDATE);var p=product(id,a.tenantId());p.checkVersion(version);p.transition(status);String action="PRODUCT_"+status.name()+(status==Product.Status.INACTIVE?"D":"");audit.record(a,action,"product",id.toString());if(status==Product.Status.ACTIVE)events.publishEvent(new CatalogEvents.ProductActivated(a.tenantId(),id));if(status==Product.Status.ARCHIVED)events.publishEvent(new CatalogEvents.ProductArchived(a.tenantId(),id));return p;}
 @Transactional ProductVariant addVariant(UUID productId,VariantInput in,List<UUID> selections){var a=auth.require(Permission.CATALOG_CREATE);product(productId,a.tenantId());var signature=signature(a.tenantId(),productId,selections);try{var v=variants.saveAndFlush(new ProductVariant(a.tenantId(),productId,in.sku(),in.displayName(),UnitOfMeasure.parse(in.baseUnit()),in.weightGrams(),in.lengthMm(),in.widthMm(),in.heightMm(),signature));audit.record(a,"VARIANT_CREATED","variant",v.id().toString());events.publishEvent(new CatalogEvents.VariantCreated(a.tenantId(),productId,v.id()));return v;}catch(DataIntegrityViolationException e){throw duplicate(e,"SKU_ALREADY_EXISTS","SKU or option combination already exists");}}
 @Transactional(readOnly=true) ProductVariant variant(UUID id){var a=auth.require(Permission.CATALOG_READ);return variant(id,a.tenantId());}
 @Transactional(readOnly=true) Page<ProductVariant> variants(UUID product,int page,int size){var a=auth.require(Permission.CATALOG_READ);product(product,a.tenantId());return variants.findAllByTenantIdAndProductId(a.tenantId(),product,PageRequest.of(Math.max(page,0),Math.min(Math.max(size,1),100)));}
 @Transactional ProductVariant updateVariant(UUID id,VariantInput in,long version){var a=auth.require(Permission.CATALOG_UPDATE);var v=variant(id,a.tenantId());v.update(in.sku(),in.displayName(),in.weightGrams(),in.lengthMm(),in.widthMm(),in.heightMm(),version);audit.record(a,"VARIANT_UPDATED","variant",id.toString());return v;}
 @Transactional ProductVariant transitionVariant(UUID id,Product.Status status,long version){var a=auth.require(status==Product.Status.ARCHIVED?Permission.CATALOG_ARCHIVE:Permission.CATALOG_UPDATE);var v=variant(id,a.tenantId());if(v.version()!=version)throw new CatalogException("CONCURRENT_MODIFICATION","Variant was modified");v.transition(status);audit.record(a,"VARIANT_"+status.name()+(status==Product.Status.INACTIVE?"D":""),"variant",id.toString());return v;}
 @Transactional Category createCategory(String name,UUID parent){var a=auth.require(Permission.CATALOG_CATEGORY_MANAGE);parent(a.tenantId(),parent);try{var c=categories.saveAndFlush(new Category(a.tenantId(),name,parent));audit.record(a,"CATEGORY_CREATED","category",c.id().toString());return c;}catch(DataIntegrityViolationException e){throw duplicate(e,"CATEGORY_ALREADY_EXISTS","Category name or slug already exists");}}
 @Transactional Category updateCategory(UUID id,String name,UUID parent,long version){var a=auth.require(Permission.CATALOG_CATEGORY_MANAGE);var c=category(id,a.tenantId());parent(a.tenantId(),parent);ensureNoCycle(a.tenantId(),id,parent);c.update(name,parent,version);audit.record(a,"CATEGORY_UPDATED","category",id.toString());return c;}
 @Transactional Category archiveCategory(UUID id){var a=auth.require(Permission.CATALOG_CATEGORY_MANAGE);var c=category(id,a.tenantId());c.archive();audit.record(a,"CATEGORY_ARCHIVED","category",id.toString());return c;}
 @Transactional(readOnly=true) Page<Category> categories(int page,int size){var a=auth.require(Permission.CATALOG_READ);return categories.findAllByTenantId(a.tenantId(),PageRequest.of(Math.max(page,0),Math.min(Math.max(size,1),100),Sort.by("name")));}
 @Transactional Brand createBrand(String name){var a=auth.require(Permission.CATALOG_BRAND_MANAGE);try{var b=brands.saveAndFlush(new Brand(a.tenantId(),name));audit.record(a,"BRAND_CREATED","brand",b.id().toString());return b;}catch(DataIntegrityViolationException e){throw duplicate(e,"BRAND_ALREADY_EXISTS","Brand already exists");}}
 @Transactional Brand updateBrand(UUID id,String name,long version){var a=auth.require(Permission.CATALOG_BRAND_MANAGE);var b=brand(id,a.tenantId());b.update(name,version);audit.record(a,"BRAND_UPDATED","brand",id.toString());return b;}
 @Transactional Brand archiveBrand(UUID id){var a=auth.require(Permission.CATALOG_BRAND_MANAGE);var b=brand(id,a.tenantId());b.archive();audit.record(a,"BRAND_ARCHIVED","brand",id.toString());return b;}
 @Transactional(readOnly=true) Page<Brand> brands(int page,int size){var a=auth.require(Permission.CATALOG_READ);return brands.findAllByTenantId(a.tenantId(),PageRequest.of(Math.max(page,0),Math.min(Math.max(size,1),100),Sort.by("name")));}
 @Transactional Barcode addBarcode(UUID variantId,String type,String value,boolean primary){var a=auth.require(Permission.CATALOG_UPDATE);variant(variantId,a.tenantId());if(primary)barcodes.findAllByTenantIdAndVariantId(a.tenantId(),variantId).forEach(Barcode::clearPrimary);try{var b=barcodes.saveAndFlush(new Barcode(a.tenantId(),variantId,Barcode.Type.valueOf(type),value,primary));audit.record(a,"BARCODE_ADDED","barcode",b.id().toString());return b;}catch(DataIntegrityViolationException e){throw duplicate(e,"BARCODE_ALREADY_EXISTS","Barcode already exists in this organization");}}
 @Transactional Barcode primary(UUID variantId,UUID barcodeId){var a=auth.require(Permission.CATALOG_UPDATE);variant(variantId,a.tenantId());var selected=barcodes.findByIdAndTenantIdAndVariantId(barcodeId,a.tenantId(),variantId).orElseThrow(()->new CatalogNotFoundException("BARCODE_NOT_FOUND","Barcode not found"));barcodes.findAllByTenantIdAndVariantId(a.tenantId(),variantId).forEach(Barcode::clearPrimary);selected.makePrimary();audit.record(a,"BARCODE_PRIMARY_CHANGED","barcode",barcodeId.toString());return selected;}
 @Transactional Barcode deactivateBarcode(UUID variantId,UUID barcodeId){var a=auth.require(Permission.CATALOG_UPDATE);variant(variantId,a.tenantId());var b=barcodes.findByIdAndTenantIdAndVariantId(barcodeId,a.tenantId(),variantId).orElseThrow(()->new CatalogNotFoundException("BARCODE_NOT_FOUND","Barcode not found"));b.deactivate();return b;}
 @Transactional(readOnly=true) List<Barcode> barcodes(UUID variantId){var a=auth.require(Permission.CATALOG_READ);variant(variantId,a.tenantId());return barcodes.findAllByTenantIdAndVariantId(a.tenantId(),variantId);}
 @Transactional(readOnly=true) ProductVariant lookup(String sku,String barcode){var a=auth.require(Permission.CATALOG_READ);if((sku==null)==(barcode==null))throw new CatalogException("INVALID_LOOKUP","Supply exactly one of sku or barcode");if(sku!=null)return variants.findByTenantIdAndNormalizedSku(a.tenantId(),CatalogRules.sku(sku)).orElseThrow(()->new CatalogNotFoundException("VARIANT_NOT_FOUND","Variant not found"));var b=barcodes.findByTenantIdAndNormalizedValueAndActiveTrue(a.tenantId(),barcode.replaceAll("\\s+","").toUpperCase()).orElseThrow(()->new CatalogNotFoundException("VARIANT_NOT_FOUND","Variant not found"));return variant(b.variant(),a.tenantId());}
 private Product product(UUID id,UUID tenant){return products.findByIdAndTenantId(id,tenant).orElseThrow(()->new CatalogNotFoundException("PRODUCT_NOT_FOUND","Product not found"));}private ProductVariant variant(UUID id,UUID tenant){return variants.findByIdAndTenantId(id,tenant).orElseThrow(()->new CatalogNotFoundException("VARIANT_NOT_FOUND","Variant not found"));}private Category category(UUID id,UUID tenant){return categories.findByIdAndTenantId(id,tenant).orElseThrow(()->new CatalogNotFoundException("CATEGORY_NOT_FOUND","Category not found"));}private Brand brand(UUID id,UUID tenant){return brands.findByIdAndTenantId(id,tenant).orElseThrow(()->new CatalogNotFoundException("BRAND_NOT_FOUND","Brand not found"));}
 private void relations(UUID t,UUID c,UUID b){if(c!=null&&category(c,t).status()!=Category.Status.ACTIVE)throw new CatalogException("CATEGORY_ARCHIVED","Category is archived");if(b!=null&&brand(b,t).status()!=Brand.Status.ACTIVE)throw new CatalogException("BRAND_ARCHIVED","Brand is archived");}private void parent(UUID t,UUID p){if(p!=null)category(p,t);}private void ensureNoCycle(UUID t,UUID id,UUID parent){var seen=new HashSet<UUID>();var p=parent;while(p!=null){if(!seen.add(p)||p.equals(id))throw new CatalogException("CATEGORY_CYCLE","Category hierarchy cycle");p=category(p,t).parent();}}
 private String signature(UUID t,UUID p,List<UUID> selected){if(selected==null||selected.isEmpty()){if(!options.findAllByTenantIdAndProductIdOrderByPosition(t,p).isEmpty())throw new CatalogException("OPTION_SELECTION_REQUIRED","Variant options required");return "DEFAULT";}var vals=selected.stream().map(id->values.findByIdAndTenantIdAndProductId(id,t,p).orElseThrow(()->new CatalogException("INVALID_OPTION_SELECTION","Option value does not belong to product"))).toList();if(vals.stream().map(v->v.optionId).distinct().count()!=vals.size())throw new CatalogException("INVALID_OPTION_SELECTION","Only one value per option is allowed");return vals.stream().sorted(Comparator.comparing(v->v.optionId)).map(v->v.optionId+"="+v.id).reduce((a,b)->a+";"+b).orElse("DEFAULT");}
 private static String blank(String s){return s==null||s.isBlank()?null:s.trim();}private static CatalogException duplicate(Exception e,String c,String m){return new CatalogException(c,m);} record VariantInput(String sku,String displayName,String baseUnit,Long weightGrams,Long lengthMm,Long widthMm,Long heightMm){}
}
