package io.invenlio.catalog;
import java.util.*; import org.springframework.data.domain.*; import org.springframework.data.jpa.repository.*; import org.springframework.data.repository.query.Param;
interface ProductRepository extends JpaRepository<Product,UUID>{Optional<Product> findByIdAndTenantId(UUID id,UUID tenantId);@Query(value="SELECT p.* FROM catalog_products p WHERE p.tenant_id=:tenantId AND (:queryText IS NULL OR lower(p.name) LIKE lower('%'||CAST(:queryText AS text)||'%') OR EXISTS (SELECT 1 FROM catalog_product_variants v WHERE v.tenant_id=p.tenant_id AND v.product_id=p.id AND lower(v.sku) LIKE lower('%'||CAST(:queryText AS text)||'%'))) AND (:statusValue IS NULL OR p.status=CAST(:statusValue AS text)) AND (:categoryId IS NULL OR p.category_id=:categoryId) AND (:brandId IS NULL OR p.brand_id=:brandId)",countQuery="SELECT count(*) FROM catalog_products p WHERE p.tenant_id=:tenantId AND (:queryText IS NULL OR lower(p.name) LIKE lower('%'||CAST(:queryText AS text)||'%') OR EXISTS (SELECT 1 FROM catalog_product_variants v WHERE v.tenant_id=p.tenant_id AND v.product_id=p.id AND lower(v.sku) LIKE lower('%'||CAST(:queryText AS text)||'%'))) AND (:statusValue IS NULL OR p.status=CAST(:statusValue AS text)) AND (:categoryId IS NULL OR p.category_id=:categoryId) AND (:brandId IS NULL OR p.brand_id=:brandId)",nativeQuery=true)Page<Product> search(@Param("tenantId")UUID tenant,@Param("queryText")String q,@Param("statusValue")String status,@Param("categoryId")UUID category,@Param("brandId")UUID brand,Pageable page);}
interface VariantRepository extends JpaRepository<ProductVariant,UUID>{Optional<ProductVariant> findByIdAndTenantId(UUID id,UUID tenant);Optional<ProductVariant> findByTenantIdAndNormalizedSku(UUID tenant,String sku);Page<ProductVariant> findAllByTenantIdAndProductId(UUID tenant,UUID product,Pageable page);}
interface CategoryRepository extends JpaRepository<Category,UUID>{Optional<Category> findByIdAndTenantId(UUID id,UUID tenant);Page<Category> findAllByTenantId(UUID tenant,Pageable page);}
interface BrandRepository extends JpaRepository<Brand,UUID>{Optional<Brand> findByIdAndTenantId(UUID id,UUID tenant);Page<Brand> findAllByTenantId(UUID tenant,Pageable page);}
interface BarcodeRepository extends JpaRepository<Barcode,UUID>{Optional<Barcode> findByIdAndTenantIdAndVariantId(UUID id,UUID tenant,UUID variant);Optional<Barcode> findByTenantIdAndNormalizedValueAndActiveTrue(UUID tenant,String value);List<Barcode> findAllByTenantIdAndVariantId(UUID tenant,UUID variant);}
interface OptionRepository extends JpaRepository<ProductOption,UUID>{Optional<ProductOption> findByIdAndTenantIdAndProductId(UUID id,UUID tenant,UUID product);List<ProductOption> findAllByTenantIdAndProductIdOrderByPosition(UUID tenant,UUID product);}
interface OptionValueRepository extends JpaRepository<ProductOptionValue,UUID>{Optional<ProductOptionValue> findByIdAndTenantIdAndProductId(UUID id,UUID tenant,UUID product);}
