package io.invenlio.catalog;
import io.swagger.v3.oas.annotations.security.SecurityRequirement; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.time.Instant; import java.util.*; import org.springframework.data.domain.Page; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1") @SecurityRequirement(name="bearerAuth") class CatalogController {
 private final CatalogService service;CatalogController(CatalogService s){service=s;}
 @PostMapping("/products") ProductView create(@Valid @RequestBody CreateProduct r){return view(service.create(r.name(),r.description(),r.categoryId(),r.brandId(),r.baseUnit(),input(r.initialVariant(),r.baseUnit())));}
 @GetMapping("/products") Page<ProductView> products(@RequestParam(required=false)String q,@RequestParam(required=false)String status,@RequestParam(required=false)UUID categoryId,@RequestParam(required=false)UUID brandId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="name")String sort){return service.search(q,status,categoryId,brandId,page,size,sort).map(CatalogController::view);}
 @GetMapping("/products/{id}") ProductView product(@PathVariable UUID id){return view(service.get(id));}
 @PatchMapping("/products/{id}") ProductView update(@PathVariable UUID id,@Valid @RequestBody UpdateProduct r){return view(service.update(id,r.name(),r.description(),r.categoryId(),r.brandId(),r.version()));}
 @PostMapping("/products/{id}/activate") ProductView activate(@PathVariable UUID id,@RequestBody VersionRequest r){return view(service.transitionProduct(id,Product.Status.ACTIVE,r.version()));}
 @PostMapping("/products/{id}/deactivate") ProductView deactivate(@PathVariable UUID id,@RequestBody VersionRequest r){return view(service.transitionProduct(id,Product.Status.INACTIVE,r.version()));}
 @PostMapping("/products/{id}/archive") ProductView archive(@PathVariable UUID id,@RequestBody VersionRequest r){return view(service.transitionProduct(id,Product.Status.ARCHIVED,r.version()));}
 @PostMapping("/products/{id}/variants") VariantView addVariant(@PathVariable UUID id,@Valid @RequestBody VariantRequest r){return view(service.addVariant(id,input(r,r.baseUnit()),r.optionValueIds()));}
 @GetMapping("/products/{id}/variants") Page<VariantView> variants(@PathVariable UUID id,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return service.variants(id,page,size).map(CatalogController::view);}
 @GetMapping("/variants/{id}") VariantView variant(@PathVariable UUID id){return view(service.variant(id));}
 @PatchMapping("/variants/{id}") VariantView updateVariant(@PathVariable UUID id,@Valid @RequestBody VariantRequest r){return view(service.updateVariant(id,input(r,r.baseUnit()),r.version()));}
 @PostMapping("/variants/{id}/activate") VariantView activateVariant(@PathVariable UUID id,@RequestBody VersionRequest r){return view(service.transitionVariant(id,Product.Status.ACTIVE,r.version()));}
 @PostMapping("/variants/{id}/deactivate") VariantView deactivateVariant(@PathVariable UUID id,@RequestBody VersionRequest r){return view(service.transitionVariant(id,Product.Status.INACTIVE,r.version()));}
 @PostMapping("/variants/{id}/archive") VariantView archiveVariant(@PathVariable UUID id,@RequestBody VersionRequest r){return view(service.transitionVariant(id,Product.Status.ARCHIVED,r.version()));}
 @GetMapping("/variants/{id}/barcodes") List<BarcodeView> barcodes(@PathVariable UUID id){return service.barcodes(id).stream().map(CatalogController::view).toList();}
 @PostMapping("/variants/{id}/barcodes") BarcodeView addBarcode(@PathVariable UUID id,@Valid @RequestBody BarcodeRequest r){return view(service.addBarcode(id,r.type(),r.value(),r.primary()));}
 @PostMapping("/variants/{id}/barcodes/{barcode}/primary") BarcodeView primary(@PathVariable UUID id,@PathVariable UUID barcode){return view(service.primary(id,barcode));}
 @PostMapping("/variants/{id}/barcodes/{barcode}/deactivate") BarcodeView deactivateBarcode(@PathVariable UUID id,@PathVariable UUID barcode){return view(service.deactivateBarcode(id,barcode));}
 @GetMapping("/catalog/lookup") VariantView lookup(@RequestParam(required=false)String sku,@RequestParam(required=false)String barcode){return view(service.lookup(sku,barcode));}
 private static CatalogService.VariantInput input(VariantRequest r,String fallback){if(r==null)return null;return new CatalogService.VariantInput(r.sku(),r.displayName(),r.baseUnit()==null?fallback:r.baseUnit(),r.weightGrams(),r.lengthMm(),r.widthMm(),r.heightMm());}
 static ProductView view(Product p){return new ProductView(p.id(),p.name(),p.description(),p.status().name(),p.category(),p.brand(),p.unit(),p.created(),p.updated(),p.version());}static VariantView view(ProductVariant v){return new VariantView(v.id(),v.product(),v.sku(),v.status().name(),v.label(),v.unit(),v.weight(),v.length(),v.width(),v.height(),v.created(),v.updated(),v.version());}static BarcodeView view(Barcode b){return new BarcodeView(b.id(),b.type().name(),b.value(),b.primary(),b.active(),b.created());}
 record CreateProduct(@NotBlank @Size(max=200)String name,@Size(max=4000)String description,UUID categoryId,UUID brandId,@NotBlank String baseUnit,@NotNull @Valid VariantRequest initialVariant){}record UpdateProduct(@NotBlank @Size(max=200)String name,@Size(max=4000)String description,UUID categoryId,UUID brandId,@PositiveOrZero long version){}record VariantRequest(@NotBlank @Size(max=80)String sku,@Size(max=200)String displayName,String baseUnit,@PositiveOrZero Long weightGrams,@PositiveOrZero Long lengthMm,@PositiveOrZero Long widthMm,@PositiveOrZero Long heightMm,List<UUID> optionValueIds,@PositiveOrZero long version){}record VersionRequest(@PositiveOrZero long version){}record BarcodeRequest(@NotBlank String type,@NotBlank @Size(max=128)String value,boolean primary){}
 record ProductView(UUID id,String name,String description,String status,UUID categoryId,UUID brandId,String baseUnit,Instant createdAt,Instant updatedAt,long version){}record VariantView(UUID id,UUID productId,String sku,String status,String displayName,String baseUnit,Long weightGrams,Long lengthMm,Long widthMm,Long heightMm,Instant createdAt,Instant updatedAt,long version){}record BarcodeView(UUID id,String type,String value,boolean primary,boolean active,Instant createdAt){}
}
