package io.invenlio.catalog;
import jakarta.persistence.*; import java.math.*; import java.time.*; import java.util.*;
@Entity @Table(name="catalog_product_variants") class ProductVariant {
 @Id private UUID id; @Column(name="tenant_id",updatable=false) private UUID tenantId; @Column(name="product_id",updatable=false) private UUID productId; private String sku; @Column(name="normalized_sku",updatable=false) private String normalizedSku;
 @Enumerated(EnumType.STRING) private Product.Status status; @Column(name="display_name") private String displayName; @Column(name="base_unit") private String baseUnit;
 @Column(name="weight_grams") private Long weightGrams; @Column(name="length_mm") private Long lengthMm; @Column(name="width_mm") private Long widthMm; @Column(name="height_mm") private Long heightMm;
 @Column(name="option_signature",updatable=false) private String optionSignature; @Column(name="standard_cost") private BigDecimal standardCost; @Column(name="list_price") private BigDecimal listPrice; private String currency;
 @Column(name="created_at",updatable=false) private Instant createdAt; @Column(name="updated_at") private Instant updatedAt; @Version private long version;
 protected ProductVariant(){} ProductVariant(UUID tenant,UUID product,String sku,String label,UnitOfMeasure unit,Long weight,Long length,Long width,Long height,String signature){id=UUID.randomUUID();tenantId=tenant;productId=product;this.sku=normalizedSku=CatalogRules.sku(sku);displayName=label==null?null:label.trim();baseUnit=unit.name();validateMeasure(weight,1_000_000_000L);validateMeasure(length,10_000_000L);validateMeasure(width,10_000_000L);validateMeasure(height,10_000_000L);weightGrams=weight;lengthMm=length;widthMm=width;heightMm=height;optionSignature=signature;status=Product.Status.DRAFT;createdAt=updatedAt=Instant.now();}
 void update(String sku,String label,Long weight,Long length,Long width,Long height,long expected){if(version!=expected)throw new CatalogException("CONCURRENT_MODIFICATION","Variant was modified by another request");var normalized=CatalogRules.sku(sku);if(status!=Product.Status.DRAFT&&!normalized.equals(normalizedSku))throw new CatalogException("SKU_IMMUTABLE","SKU is immutable after activation");validateMeasure(weight,1_000_000_000L);validateMeasure(length,10_000_000L);validateMeasure(width,10_000_000L);validateMeasure(height,10_000_000L);this.sku=normalized;displayName=label;weightGrams=weight;lengthMm=length;widthMm=width;heightMm=height;updatedAt=Instant.now();}
 void transition(Product.Status next){boolean ok=switch(status){case DRAFT->next==Product.Status.ACTIVE||next==Product.Status.ARCHIVED;case ACTIVE->next==Product.Status.INACTIVE;case INACTIVE->next==Product.Status.ACTIVE||next==Product.Status.ARCHIVED;case ARCHIVED->false;};if(!ok)throw new CatalogException("INVALID_VARIANT_STATUS_TRANSITION","Invalid variant lifecycle transition");status=next;updatedAt=Instant.now();}
 private static void validateMeasure(Long v,long max){if(v!=null&&(v<0||v>max))throw new CatalogException("INVALID_PHYSICAL_MEASURE","Physical measure outside supported bounds");}
 UUID id(){return id;} UUID product(){return productId;} String sku(){return sku;} Product.Status status(){return status;} String label(){return displayName;} String unit(){return baseUnit;} Long weight(){return weightGrams;} Long length(){return lengthMm;} Long width(){return widthMm;} Long height(){return heightMm;} String signature(){return optionSignature;} Instant created(){return createdAt;} Instant updated(){return updatedAt;} long version(){return version;}
}
